.TH "Address" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Address \- 
.PP
Structure for \fBAddress\fP objects.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Address.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBVersionChecksumBytes\fP \fBbase\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for \fBAddress\fP objects. 

\fBSee also:\fP
.RS 4
\fBAddress.h\fP 
.RE
.PP

.PP
Definition at line 28 of file Address.h.
.SH "Field Documentation"
.PP 
.SS "\fBVersionChecksumBytes\fP \fBbase\fP"\fBVersionChecksumBytes\fP base structure 
.PP
Definition at line 29 of file Address.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
