.TH "src/Bitcoin.c" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Bitcoin.c \- 
.PP
A test case for \fBBlock\fP.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A test case for \fBBlock\fP. 

Test the \fBBlock\fP class 
.PP
Definition in file \fBBitcoin.c\fP.
.SH "Function Documentation"
.PP 
.SS "int main (void)"@ brief main function in testBlock 
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 21 of file Bitcoin.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
