.TH "BlockSpck" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockSpck \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBversion\fP"
.br
.ti -1c
.RI "unsigned int \fBstartCount\fP"
.br
.ti -1c
.RI "char \fBblockLocatorHashes\fP [32]"
.br
.ti -1c
.RI "char \fBhashStop\fP [32]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file Protocol.h.
.SH "Field Documentation"
.PP 
.SS "char \fBblockLocatorHashes\fP[32]"
.PP
Definition at line 130 of file Protocol.h.
.SS "char \fBhashStop\fP[32]"
.PP
Definition at line 131 of file Protocol.h.
.SS "unsigned int \fBstartCount\fP"
.PP
Definition at line 129 of file Protocol.h.
.SS "unsigned int \fBversion\fP"
.PP
Definition at line 128 of file Protocol.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
