.TH "CmdAddr" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdAddr \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Commands.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBcount\fP"
.br
.ti -1c
.RI "uint32_t * \fBtslist\fP"
.br
.ti -1c
.RI "struct \fBNetworkAddress\fP * \fBnaddrlist\fP"
.br
.ti -1c
.RI "unsigned int \fBcount\fP"
.br
.ti -1c
.RI "unsigned int * \fBtslist\fP"
.br
.ti -1c
.RI "struct \fBNetAddr\fP * \fBnaddrlist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 101 of file Commands.h.
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBcount\fP"
.PP
Definition at line 104 of file Commands.h.
.SS "unsigned int \fBcount\fP"
.PP
Definition at line 101 of file Protocol.h.
.SS "struct \fBNetAddr\fP* \fBnaddrlist\fP"
.PP
Definition at line 106 of file Protocol.h.
.SS "struct \fBNetworkAddress\fP* \fBnaddrlist\fP"
.PP
Definition at line 109 of file Commands.h.
.SS "uint32_t* \fBtslist\fP"
.PP
Definition at line 107 of file Commands.h.
.SS "unsigned int* \fBtslist\fP"
.PP
Definition at line 104 of file Protocol.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
