.TH "Cmdblock" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cmdblock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Commands.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBversion\fP"
.br
.ti -1c
.RI "char \fBprev_block\fP [32]"
.br
.ti -1c
.RI "char \fBmarkle_root\fP [32]"
.br
.ti -1c
.RI "uint32_t \fBtimestamp\fP"
.br
.ti -1c
.RI "uint32_t \fBbits\fP"
.br
.ti -1c
.RI "uint32_t \fBnonce\fP"
.br
.ti -1c
.RI "uint32_t \fBtxnCount\fP"
.br
.ti -1c
.RI "struct tx * \fBtxns\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 151 of file Commands.h.
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBbits\fP"
.PP
Definition at line 157 of file Commands.h.
.SS "char \fBmarkle_root\fP[32]"
.PP
Definition at line 155 of file Commands.h.
.SS "uint32_t \fBnonce\fP"
.PP
Definition at line 158 of file Commands.h.
.SS "char \fBprev_block\fP[32]"
.PP
Definition at line 154 of file Commands.h.
.SS "uint32_t \fBtimestamp\fP"
.PP
Definition at line 156 of file Commands.h.
.SS "uint32_t \fBtxnCount\fP"
.PP
Definition at line 159 of file Commands.h.
.SS "struct tx* \fBtxns\fP"
.PP
Definition at line 160 of file Commands.h.
.SS "uint32_t \fBversion\fP"
.PP
Definition at line 153 of file Commands.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
