.TH "CmdGetBlocks" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdGetBlocks \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Commands.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBversion\fP"
.br
.ti -1c
.RI "uint32_t \fBstartCount\fP"
.br
.ti -1c
.RI "char \fBblockLocatorHashes\fP [32]"
.br
.ti -1c
.RI "char \fBhashStop\fP [32]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file Commands.h.
.SH "Field Documentation"
.PP 
.SS "char \fBblockLocatorHashes\fP[32]"
.PP
Definition at line 131 of file Commands.h.
.SS "char \fBhashStop\fP[32]"
.PP
Definition at line 132 of file Commands.h.
.SS "uint32_t \fBstartCount\fP"
.PP
Definition at line 130 of file Commands.h.
.SS "uint32_t \fBversion\fP"
.PP
Definition at line 129 of file Commands.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
