.TH "CmdGetData" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdGetData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Commands.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBcount\fP"
.br
.ti -1c
.RI "struct \fBInventoryVector\fP * \fBInvVect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 119 of file Commands.h.
.SH "Field Documentation"
.PP 
.SS "uint64_t \fBcount\fP"
.PP
Definition at line 121 of file Commands.h.
.SS "struct \fBInventoryVector\fP* \fBInvVect\fP"
.PP
Definition at line 124 of file Commands.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
