.TH "CmdHeaderCheckSum" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdHeaderCheckSum \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBmagic\fP"
.br
.ti -1c
.RI "char \fBcommand\fP [12]"
.br
.ti -1c
.RI "unsigned int \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file Protocol.h.
.SH "Field Documentation"
.PP 
.SS "char \fBcommand\fP[12]"
.PP
Definition at line 52 of file Protocol.h.
.SS "unsigned int \fBlength\fP"
.PP
Definition at line 53 of file Protocol.h.
.SS "unsigned int \fBmagic\fP"
.PP
Definition at line 51 of file Protocol.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
