.TH "CmdInv" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdInv \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Commands.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.ti -1c
.RI "char \fBhash\fP [32]"
.br
.ti -1c
.RI "unsigned int \fBcount\fP"
.br
.ti -1c
.RI "struct \fBInventoryVector\fP * \fBInventoryVectors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file Commands.h.
.SH "Field Documentation"
.PP 
.SS "unsigned int \fBcount\fP"
.PP
Definition at line 121 of file Protocol.h.
.SS "char \fBhash\fP[32]"
.PP
Definition at line 116 of file Commands.h.
.SS "struct \fBInventoryVector\fP* \fBInventoryVectors\fP"
.PP
Definition at line 122 of file Protocol.h.
.SS "uint32_t \fBtype\fP"
.PP
Definition at line 114 of file Commands.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
