.TH "CmdTranx" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdTranx \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Commands.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBversion\fP"
.br
.ti -1c
.RI "uint32_t \fBTranxIn_count\fP"
.br
.ti -1c
.RI "struct \fBTranxIn\fP * \fBTranxInput\fP"
.br
.ti -1c
.RI "uint32_t \fBTranxOut_count\fP"
.br
.ti -1c
.RI "struct \fBTranxOut\fP * \fBTranxOutput\fP"
.br
.ti -1c
.RI "uint32_t \fBlock_time\fP"
.br
.ti -1c
.RI "unsigned int \fBversion\fP"
.br
.ti -1c
.RI "unsigned int \fBtranxInCount\fP"
.br
.ti -1c
.RI "unsigned int \fBtranxOutCount\fP"
.br
.ti -1c
.RI "unsigned int \fBlockTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 142 of file Commands.h.
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBlock_time\fP"
.PP
Definition at line 148 of file Commands.h.
.SS "unsigned int \fBlockTime\fP"
.PP
Definition at line 178 of file Protocol.h.
.SS "uint32_t \fBTranxIn_count\fP"
.PP
Definition at line 144 of file Commands.h.
.SS "unsigned int \fBtranxInCount\fP"
.PP
Definition at line 174 of file Protocol.h.
.SS "struct \fBTranxIn\fP * \fBTranxInput\fP"
.PP
Definition at line 145 of file Commands.h.
.SS "uint32_t \fBTranxOut_count\fP"
.PP
Definition at line 146 of file Commands.h.
.SS "unsigned int \fBtranxOutCount\fP"
.PP
Definition at line 176 of file Protocol.h.
.SS "struct \fBTranxOut\fP * \fBTranxOutput\fP"
.PP
Definition at line 147 of file Commands.h.
.SS "unsigned int \fBversion\fP"
.PP
Definition at line 173 of file Protocol.h.
.SS "uint32_t \fBversion\fP"
.PP
Definition at line 143 of file Commands.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
