.TH "CmdVersion" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdVersion \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Commands.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBversion\fP"
.br
.ti -1c
.RI "uint64_t \fBservices\fP"
.br
.ti -1c
.RI "int64_t \fBtimestamp\fP"
.br
.ti -1c
.RI "struct \fBNetworkAddress\fP \fBaddrRecv\fP"
.br
.ti -1c
.RI "struct \fBNetworkAddress\fP \fBaddrFrom\fP"
.br
.ti -1c
.RI "uint64_t \fBnonce\fP"
.br
.ti -1c
.RI "char * \fBsubVersionNum\fP"
.br
.ti -1c
.RI "int32_t \fBstartHeight\fP"
.br
.ti -1c
.RI "unsigned int \fBversion\fP"
.br
.ti -1c
.RI "long int \fBservices\fP"
.br
.ti -1c
.RI "long int \fBtimestamp\fP"
.br
.ti -1c
.RI "struct \fBNetAddr\fP \fBaddrRecv\fP"
.br
.ti -1c
.RI "struct \fBNetAddr\fP \fBaddrFrom\fP"
.br
.ti -1c
.RI "long int \fBnonce\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file Commands.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBNetworkAddress\fP \fBaddrFrom\fP"
.PP
Definition at line 73 of file Commands.h.
.SS "struct \fBNetAddr\fP \fBaddrFrom\fP"
.PP
Definition at line 76 of file Protocol.h.
.SS "struct \fBNetworkAddress\fP \fBaddrRecv\fP"
.PP
Definition at line 68 of file Commands.h.
.SS "struct \fBNetAddr\fP \fBaddrRecv\fP"
.PP
Definition at line 73 of file Protocol.h.
.SS "uint64_t \fBnonce\fP"
.PP
Definition at line 79 of file Commands.h.
.SS "long int \fBnonce\fP"
.PP
Definition at line 77 of file Protocol.h.
.SS "uint64_t \fBservices\fP"
.PP
Definition at line 62 of file Commands.h.
.SS "long int \fBservices\fP"
.PP
Definition at line 71 of file Protocol.h.
.SS "int32_t \fBstartHeight\fP"
.PP
Definition at line 87 of file Commands.h.
.SS "char* \fBsubVersionNum\fP"
.PP
Definition at line 82 of file Commands.h.
.SS "long int \fBtimestamp\fP"
.PP
Definition at line 72 of file Protocol.h.
.SS "int64_t \fBtimestamp\fP"
.PP
Definition at line 65 of file Commands.h.
.SS "int32_t \fBversion\fP"
.PP
Definition at line 59 of file Commands.h.
.SS "unsigned int \fBversion\fP"
.PP
Definition at line 70 of file Protocol.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
