.TH "CmdVerack" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdVerack \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Commands.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBmagic\fP"
.br
.ti -1c
.RI "char \fBcommand\fP [12]"
.br
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.ti -1c
.RI "uint32_t \fBchecksum\fP"
.br
.ti -1c
.RI "unsigned char * \fBpayload\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file Commands.h.
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBchecksum\fP"
.PP
Definition at line 97 of file Commands.h.
.SS "char \fBcommand\fP[12]"
.PP
Definition at line 95 of file Commands.h.
.SS "uint32_t \fBlength\fP"
.PP
Definition at line 96 of file Commands.h.
.SS "uint32_t \fBmagic\fP"
.PP
Definition at line 92 of file Commands.h.
.SS "unsigned char* \fBpayload\fP"
.PP
Definition at line 98 of file Commands.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
