.TH "Header" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Header \- 
.PP
Structure for \fBTransaction\fP objects; contains all the fields defined in the bitcoin protocol.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Structure for \fBTransaction\fP objects; contains all the fields defined in the bitcoin protocol. 

the \fBTransaction\fP \fBObject\fP; contains the \fBTransaction\fP base structure. 
.PP
\fBSee also:\fP
.RS 4
\fBTransaction.h\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
