.TH "HeaderSpck" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeaderSpck \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBstartCount\fP"
.br
.ti -1c
.RI "char \fBhashStart\fP [32]"
.br
.ti -1c
.RI "char \fBhashStop\fP [32]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 137 of file Protocol.h.
.SH "Field Documentation"
.PP 
.SS "char \fBhashStart\fP[32]"
.PP
Definition at line 139 of file Protocol.h.
.SS "char \fBhashStop\fP[32]"
.PP
Definition at line 140 of file Protocol.h.
.SS "int \fBstartCount\fP"
.PP
Definition at line 138 of file Protocol.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
