.TH "src/IbTest.c" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/IbTest.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmyClass\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char \fBString\fP [1000]"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef char \fBString\fP[1000]"
.PP
Definition at line 4 of file IbTest.c.
.SH "Function Documentation"
.PP 
.SS "int main (void)"
.PP
Definition at line 11 of file IbTest.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
