.TH "Inventory" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inventory \- 
.PP
Structure for \fBInventory\fP objects.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventory.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMessage\fP \fBbase\fP"
.br
.ti -1c
.RI "uint16_t \fBcount\fP"
.br
.ti -1c
.RI "\fBInventoryVector\fP ** \fBinventory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for \fBInventory\fP objects. 

\fBSee also:\fP
.RS 4
\fBInventory.h\fP 
.RE
.PP

.PP
Definition at line 26 of file Inventory.h.
.SH "Field Documentation"
.PP 
.SS "\fBMessage\fP \fBbase\fP"\fBMessage\fP base structure 
.PP
Definition at line 27 of file Inventory.h.
.SS "uint16_t \fBcount\fP"Number of inventory entries. 
.PP
Definition at line 28 of file Inventory.h.
.SS "\fBInventoryVector\fP** \fBinventory\fP"The \fBInventory\fP vectors. This should be a memory block of pointers to InventoryVectors. It will be freed when the \fBInventory\fP is freed. When adding an item it should be retained. When removing an item it should be released. Leave or set as NULL if empty. 
.PP
Definition at line 29 of file Inventory.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
