.TH "src/Object/NetworkProtocol/IRC.c" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Object/NetworkProtocol/IRC.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <netdb.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <arpa/inet.h>\fP
.br
\fC#include 'IRC.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBircDisconnect\fP (int sock)"
.br
.ti -1c
.RI "char ** \fBbootstrap\fP (char *chan)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char** bootstrap (char *chan)"
.PP
Definition at line 114 of file IRC.c.
.SS "int ircDisconnect (intsock)"
.PP
Definition at line 85 of file IRC.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
