.TH "src/Object/NetworkProtocol/IRC.h" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Object/NetworkProtocol/IRC.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_LINE_LENGTH\fP   2056"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MAX_LINE_LENGTH   2056"
.PP
Definition at line 12 of file IRC.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
