.TH "IrcAddr" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IrcAddr \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBip\fP"
.br
.ti -1c
.RI "short \fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file Protocol.h.
.SH "Field Documentation"
.PP 
.SS "int \fBip\fP"
.PP
Definition at line 22 of file Protocol.h.
.SS "short \fBport\fP"
.PP
Definition at line 23 of file Protocol.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
