.TH "BigInt/BigInt.h" 3 "Thu Oct 11 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BigInt/BigInt.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '../Constants.h'\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <stdint.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBigInt\fP"
.br
.RI "\fIContains byte data with the length of this data to represent a large integer. The byte data is in little-endian which stores the smallest byte first. On an error data is set to NULL and length is 0. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
