.TH "ScriptByteVector" 3 "Thu Oct 11 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScriptByteVector \- 
.PP
Structure for a byte vector; Byte vectors are interpreted as little-endian variable-length integers with the most significant bit determining the sign of the integer.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Script.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.ti -1c
.RI "uint16_t \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for a byte vector; Byte vectors are interpreted as little-endian variable-length integers with the most significant bit determining the sign of the integer. 
.PP
Definition at line 25 of file Script.h.
.SH "Field Documentation"
.PP 
.SS "uint8_t* \fBdata\fP"Data for this byte vector 
.PP
Definition at line 26 of file Script.h.
.SS "uint16_t \fBlength\fP"Length of this byte vector 
.PP
Definition at line 27 of file Script.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
