.TH "Object/Script.c" 3 "Thu Oct 11 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Object/Script.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Script.h'\fP
.br
\fC#include 'assert.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBScript\fP * \fBcreateNewScriptFromReference\fP (\fBByteArray\fP *program, uint32_t offset, uint32_t len)"
.br
.RI "\fICreates a new Script object. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBScript\fP* createNewScriptFromReference (\fBByteArray\fP *program, uint32_toffset, uint32_tlen)"
.PP
Creates a new Script object. Constructor 
.PP
Definition at line 15 of file Script.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
