.TH "ScriptStack" 3 "Thu Oct 11 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScriptStack \- 
.PP
Structure that holds byte vector data in a stack.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Script.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBScriptByteVector\fP * \fBelements\fP"
.br
.ti -1c
.RI "uint16_t \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that holds byte vector data in a stack. 
.PP
Definition at line 34 of file Script.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBScriptByteVector\fP* \fBelements\fP"Elements in the stack 
.PP
Definition at line 35 of file Script.h.
.SS "uint16_t \fBlength\fP"Length of the stack 
.PP
Definition at line 36 of file Script.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
