.TH "TransactionOutput" 3 "Thu Oct 11 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionOutput \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TransactionOutput.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMessage\fP \fBbase\fP"
.br
.ti -1c
.RI "uint64_t \fBvalue\fP"
.br
.ti -1c
.RI "\fBScript\fP * \fBscriptObject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file TransactionOutput.h.
.SH "Field Documentation"
.PP 
.SS "\fBMessage\fP \fBbase\fP"CBMessage base structure 
.PP
Definition at line 18 of file TransactionOutput.h.
.SS "\fBScript\fP* \fBscriptObject\fP"The output script object 
.PP
Definition at line 20 of file TransactionOutput.h.
.SS "uint64_t \fBvalue\fP"The transaction value 
.PP
Definition at line 19 of file TransactionOutput.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
