.TH "myClass" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myClass \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file IbTest.c.
.SH "Field Documentation"
.PP 
.SS "int \fBid\fP"
.PP
Definition at line 7 of file IbTest.c.
.SS "char* \fBname\fP"
.PP
Definition at line 8 of file IbTest.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
