.TH "NetAddr" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetAddr \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBtime\fP"
.br
.ti -1c
.RI "long int \fBservices\fP"
.br
.ti -1c
.RI "unsigned char \fBip\fP [16]"
.br
.ti -1c
.RI "unsigned short \fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file Protocol.h.
.SH "Field Documentation"
.PP 
.SS "unsigned char \fBip\fP[16]"
.PP
Definition at line 33 of file Protocol.h.
.SS "unsigned short \fBport\fP"
.PP
Definition at line 34 of file Protocol.h.
.SS "long int \fBservices\fP"
.PP
Definition at line 32 of file Protocol.h.
.SS "unsigned int \fBtime\fP"
.PP
Definition at line 31 of file Protocol.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
