.TH "NetworkAddress" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetworkAddress \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Commands.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBtime\fP"
.br
.ti -1c
.RI "uint64_t \fBservices\fP"
.br
.ti -1c
.RI "char \fBip\fP [16]"
.br
.ti -1c
.RI "uint16_t \fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Commands.h.
.SH "Field Documentation"
.PP 
.SS "char \fBip\fP[16]"
.PP
Definition at line 24 of file Commands.h.
.SS "uint16_t \fBport\fP"
.PP
Definition at line 25 of file Commands.h.
.SS "uint64_t \fBservices\fP"
.PP
Definition at line 23 of file Commands.h.
.SS "uint32_t \fBtime\fP"
.PP
Definition at line 22 of file Commands.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
