.TH "NodeDiscovery" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeDiscovery \- 
.PP
Structure for \fBNodeDiscovery\fP objects.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NodeDiscovery.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBObject\fP \fBbase\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for \fBNodeDiscovery\fP objects. 

\fBSee also:\fP
.RS 4
\fBNodeDiscovery.h\fP 
.RE
.PP

.PP
Definition at line 32 of file NodeDiscovery.h.
.SH "Field Documentation"
.PP 
.SS "\fBObject\fP \fBbase\fP"\fBObject\fP base structure 
.PP
Definition at line 33 of file NodeDiscovery.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
