.TH "Outpoint" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpoint \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Commands.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBhash\fP [32]"
.br
.ti -1c
.RI "uint32_t \fBindex\fP"
.br
.ti -1c
.RI "unsigned int \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file Commands.h.
.SH "Field Documentation"
.PP 
.SS "char \fBhash\fP"
.PP
Definition at line 44 of file Commands.h.
.SS "unsigned int \fBindex\fP"
.PP
Definition at line 148 of file Protocol.h.
.SS "uint32_t \fBindex\fP"
.PP
Definition at line 45 of file Commands.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
