.TH "PingPongMessage" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PingPongMessage \- 
.PP
Structure for \fBPingPongMessage\fP objects.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PingPongMessage.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMessage\fP \fBbase\fP"
.br
.ti -1c
.RI "uint64_t \fBnonceID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for \fBPingPongMessage\fP objects. 

\fBSee also:\fP
.RS 4
\fBPingPongMessage.h\fP 
.RE
.PP

.PP
Definition at line 28 of file PingPongMessage.h.
.SH "Field Documentation"
.PP 
.SS "\fBMessage\fP \fBbase\fP"\fBMessage\fP base structure 
.PP
Definition at line 29 of file PingPongMessage.h.
.SS "uint64_t \fBnonceID\fP"Used to identify a ping/pong. Set ping to zero if no identification is needed. Set pongs to the same as the request ping. 
.PP
Definition at line 30 of file PingPongMessage.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
