.TH "src/Object/NetworkProtocol/Protocol.h" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Object/NetworkProtocol/Protocol.h \- 
.PP
This class is responsible for the Protocol functionality described in the Bitcoin.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBIrcAddr\fP"
.br
.ti -1c
.RI "struct \fBNetAddr\fP"
.br
.ti -1c
.RI "struct \fBCmdHeader\fP"
.br
.ti -1c
.RI "struct \fBCmdHeaderCheckSum\fP"
.br
.ti -1c
.RI "struct \fBCmdVersion\fP"
.br
.ti -1c
.RI "struct \fBBlockHeader\fP"
.br
.ti -1c
.RI "struct \fBCmdAddr\fP"
.br
.ti -1c
.RI "struct \fBInventoryVector\fP"
.br
.RI "\fIStructure for \fBInventoryVector\fP objects. \fP"
.ti -1c
.RI "struct \fBCmdInv\fP"
.br
.ti -1c
.RI "struct \fBBlockSpck\fP"
.br
.ti -1c
.RI "struct \fBHeaderSpck\fP"
.br
.ti -1c
.RI "struct \fBOutpoint\fP"
.br
.ti -1c
.RI "struct \fBTranxIn\fP"
.br
.ti -1c
.RI "struct \fBTranxOut\fP"
.br
.ti -1c
.RI "struct \fBCmdTranx\fP"
.br
.ti -1c
.RI "struct \fBCmdBlock\fP"
.br
.ti -1c
.RI "struct \fBHeaders\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is responsible for the Protocol functionality described in the Bitcoin. 


.PP
Definition in file \fBProtocol.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
