.TH "SharedData" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedData \- 
.PP
Stores byte data that can be shared amongst many ByteArrays.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ByteArray.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.ti -1c
.RI "uint32_t \fBreferenceCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores byte data that can be shared amongst many ByteArrays. 
.PP
Definition at line 21 of file ByteArray.h.
.SH "Field Documentation"
.PP 
.SS "uint8_t* \fBdata\fP"Pointer to byte data 
.PP
Definition at line 22 of file ByteArray.h.
.SS "uint32_t \fBreferenceCount\fP"References to this data 
.PP
Definition at line 23 of file ByteArray.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
