.TH "TranxOut" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TranxOut \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Commands.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBvalue\fP"
.br
.ti -1c
.RI "uint32_t \fBpkScriptLength\fP"
.br
.ti -1c
.RI "unsigned char \fBpkScript\fP []"
.br
.ti -1c
.RI "unsigned int \fBvalue\fP"
.br
.ti -1c
.RI "unsigned int \fBpkScriptLength\fP"
.br
.ti -1c
.RI "unsigned char * \fBpkScript\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file Commands.h.
.SH "Field Documentation"
.PP 
.SS "unsigned char \fBpkScript\fP[]"
.PP
Definition at line 51 of file Commands.h.
.SS "unsigned char* \fBpkScript\fP"
.PP
Definition at line 166 of file Protocol.h.
.SS "unsigned int \fBpkScriptLength\fP"
.PP
Definition at line 165 of file Protocol.h.
.SS "uint32_t \fBpkScriptLength\fP"
.PP
Definition at line 50 of file Commands.h.
.SS "unsigned int \fBvalue\fP"
.PP
Definition at line 164 of file Protocol.h.
.SS "uint64_t \fBvalue\fP"
.PP
Definition at line 49 of file Commands.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
