.TH "Transaction" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transaction \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Transaction.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMessage\fP \fBbase\fP"
.br
.ti -1c
.RI "uint8_t \fBhash\fP [32]"
.br
.ti -1c
.RI "uint32_t \fBversion\fP"
.br
.ti -1c
.RI "uint32_t \fBnumOfTransactionInput\fP"
.br
.ti -1c
.RI "\fBTransactionInput\fP ** \fBinputs\fP"
.br
.ti -1c
.RI "uint32_t \fBnumOfTransactionOutput\fP"
.br
.ti -1c
.RI "\fBTransactionOutput\fP ** \fBoutputs\fP"
.br
.ti -1c
.RI "uint32_t \fBlockTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file Transaction.h.
.SH "Field Documentation"
.PP 
.SS "\fBMessage\fP \fBbase\fP"\fBMessage\fP base structure> 
.PP
Definition at line 29 of file Transaction.h.
.SS "uint8_t \fBhash\fP[32]"The hash for this transaction. Null by default 
.PP
Definition at line 30 of file Transaction.h.
.SS "\fBTransactionInput\fP** \fBinputs\fP"\fBTransactionInput\fP base structure 
.PP
Definition at line 33 of file Transaction.h.
.SS "uint32_t \fBlockTime\fP"The block number or timestamp at which this transaction is locked; A non-locked transaction must not be included in blocks. 
.PP
Definition at line 36 of file Transaction.h.
.SS "uint32_t \fBnumOfTransactionInput\fP"Number of TransactionInputs. How many inputs are already added to the transaction 
.PP
Definition at line 32 of file Transaction.h.
.SS "uint32_t \fBnumOfTransactionOutput\fP"Number of TransactionOutputs. How many outputs are already added to the transaction 
.PP
Definition at line 34 of file Transaction.h.
.SS "\fBTransactionOutput\fP** \fBoutputs\fP"\fBTransactionOutput\fP base structure 
.PP
Definition at line 35 of file Transaction.h.
.SS "uint32_t \fBversion\fP"Version of the transaction data format. 1 by default 
.PP
Definition at line 31 of file Transaction.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
