.TH "VersionChecksumBytes" 3 "Fri Nov 9 2012" "Version 1.0" "Bitcoin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VersionChecksumBytes \- 
.PP
Structure for \fBVersionChecksumBytes\fP objects.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VersionChecksumBytes.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteArray\fP \fBbase\fP"
.br
.ti -1c
.RI "int \fBcacheString\fP"
.br
.ti -1c
.RI "\fBByteArray\fP * \fBcachedString\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for \fBVersionChecksumBytes\fP objects. 

\fBSee also:\fP
.RS 4
\fBVersionChecksumBytes.h\fP 
.RE
.PP

.PP
Definition at line 25 of file VersionChecksumBytes.h.
.SH "Field Documentation"
.PP 
.SS "\fBByteArray\fP \fBbase\fP"\fBByteArray\fP base structure 
.PP
Definition at line 26 of file VersionChecksumBytes.h.
.SS "\fBByteArray\fP* \fBcachedString\fP"Pointer to cached \fBByteArray\fP string 
.PP
Definition at line 28 of file VersionChecksumBytes.h.
.SS "int \fBcacheString\fP"If true, cache string 
.PP
Definition at line 27 of file VersionChecksumBytes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bitcoin from the source code.
