Base58.h
const char base58Characters[58][58]
BigInt DecodeBase58(char *str)
Decodes base 58 string into byte data as a BigInt.
str Base 58 string to decode. Pointer to the byte data as a BigInt. The byte data will be created in this function. Remember to free the data. On error the big int will have a NULL data pointer.
References BigIntEqualsAdditionByBigInt, BigIntEqualsMultiplicationByUInt8, BigIntFromPowUInt8, BigInt::data, BigInt::length.
Referenced by DecodeBase58Checked.
BigInt DecodeBase58Checked(char *str, void(*onErrorReceived)(Error error, char *,...))
Decodes base 58 string into byte data as a BigInt and checks a 4 byte checksum.
str Base 58 string to decode. Byte data as a BigInt. Is zero on failure. Checksum is included in returned data. On error the big int will have a NULL data pointer.
References BigInt::data, DecodeBase58, ERROR_BASE58_DECODE_CHECK_INVALID, ERROR_BASE58_DECODE_CHECK_TOO_SHORT, BigInt::length, VerifyAndRemoveCheckSum.
char* EncodeBase58(uint8_t *bytes, uint8_t len)
Encodes byte data into base 58.
bytes Pointer to byte data to encode. Will almost certainly be modified. Copy data beforehand if needed. len Length of bytes to encode. Newly allocated string with encoded data or NULL on error.
References BigIntCompareTo58, BigIntEqualsDivisionBy58, BigIntEqualsSubtractionByUInt8, BigIntModuloWith58, BigIntNormalise, BigInt::data, BigInt::length.
uint8_t* GetCheckSum(uint8_t *data)
References Sha256.
Referenced by VerifyAndRemoveCheckSum.
uint8_t* VerifyAndRemoveCheckSum(uint8_t *data)
References GetCheckSum.
Referenced by DecodeBase58Checked.