BigInt.c
int BigIntAlloc(BigInt *bi, uint8_t length)
References BigInt::data, BigInt::length.
Referenced by InitVersionChecksumBytesFromString.
int BigIntRealloc(BigInt *bi, uint8_t length)
References BigInt::data, BigInt::length.
Referenced by BigIntEqualsAdditionByBigInt, BigIntEqualsMultiplicationByUInt8.
Compare BigIntCompareTo58(BigInt *a)
References COMPARE_EQUAL, COMPARE_LESS_THAN, COMPARE_MORE_THAN, BigInt::data, BigInt::length.
Referenced by EncodeBase58.
int BigIntEqualsAdditionByBigInt(BigInt *a, BigInt *b)
References BigIntRealloc, BigInt::data, BigInt::length.
Referenced by DecodeBase58.
void BigIntEqualsDivisionBy58(BigInt *a, uint8_t *ans)
References BigInt::data, BigInt::length.
Referenced by EncodeBase58.
int BigIntEqualsMultiplicationByUInt8(BigInt *a, uint8_t b, uint8_t *ans)
References BigIntRealloc, BigInt::data, BigInt::length.
Referenced by BigIntFromPowUInt8, DecodeBase58.
void BigIntEqualsSubtractionByUInt8(BigInt *a, uint8_t b)
References BigIntNormalise, BigInt::data, BigInt::length.
Referenced by EncodeBase58.
int BigIntFromPowUInt8(BigInt *bi, uint8_t a, uint8_t b)
References BigIntEqualsMultiplicationByUInt8, BigInt::data, BigInt::length.
Referenced by DecodeBase58.
uint8_t BigIntModuloWith58(BigInt *a)
References BigInt::data, BigInt::length.
Referenced by EncodeBase58.
void BigIntNormalise(BigInt *a)
References BigInt::data, BigInt::length.
Referenced by BigIntEqualsSubtractionByUInt8, EncodeBase58.