BlockHeaders.c
BlockHeaders* newBlockHeaders(void(*onErrorReceived)(Error error, char *,...))
Creates a new BlockHeaders object.
A new BlockHeaders object.
References Object::destroy, ERROR_OUT_OF_MEMORY, freeBlockHeaders, getObject, initBlockHeaders.
BlockHeaders* newBlockHeadersFromData(ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new BlockHeaders object from serialized data.
data Serialized BlockHeaders data. A new BlockHeaders object.
References Object::destroy, ERROR_OUT_OF_MEMORY, freeBlockHeaders, getObject, initBlockHeadersFromData.
BlockHeaders* getBlockHeaders(void *self)
Gets a BlockHeaders from another object. Use this to avoid casts.
self The object to obtain the BlockHeaders from. The BlockHeaders object.
int initBlockHeaders(BlockHeaders *self, void(*onErrorReceived)(Error error, char *,...))
Initializes a BlockHeaders object.
self The BlockHeaders object to initialize true on success, false on failure.
References FALSE, getMessage, initializeMessageFromObject, TRUE.
Referenced by newBlockHeaders.
int initBlockHeadersFromData(BlockHeaders *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initializes a BlockHeaders object from serialized data.
self The BlockHeaders object to initialize data The serialized data. true on success, false on failure.
References FALSE, getMessage, initializeMessageFromByteArrayData, TRUE.
Referenced by newBlockHeadersFromData.
void freeBlockHeaders(void *vself)
Frees a BlockHeaders object.
self The BlockHeaders object to free.
References destroyMessage, destroyObject.
Referenced by newBlockHeaders, newBlockHeadersFromData.
int addBlockHeaderToBlockHeaderList(BlockHeaders *self, Block *header)
Adds a Block into the block header list.
self The BlockHeaders object address The Block to add. true if the block header was added successfully or false on error.
References incrementReferenceCount, takeBlockFromBlockHeaderList.
uint32_t calculateBlockHeadersLength(BlockHeaders *self)
Calculates the length needed to serialize the object.
self The BlockHeaders object. The length read on success, 0 on failure.
References getSizeOfVarLenInt.
uint32_t deserializeBlockHeaders(BlockHeaders *self)
Deserializes a BlockHeaders so that it can be used as an object.
self The BlockHeaders object The length read on success, 0 on failure.
References Message::bytes, createNewBlockFromByteArray, decodeVarLenInt, deserializeBlock, destroyObject, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, ERROR_OUT_OF_MEMORY, getByteArraySubsectionReference, getMessage, ByteArray::length, Message::onErrorReceived, VarLenInt::storageSize, VarLenInt::value.
uint32_t serializeBlockHeaders(BlockHeaders *self)
Serializes a BlockHeaders to the byte data.
self The BlockHeaders object The length written on success, 0 on failure.
References Message::bytes, createVarLenIntFromUInt64, destroyObject, encodeVarLenInt, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_NULL_BYTES, getByteArraySubsectionReference, getMessage, ByteArray::length, Message::onErrorReceived, serializeBlock, VarLenInt::storageSize, VarLenInt::value.
int takeBlockFromBlockHeaderList(BlockHeaders *self, Block *header)
Takes a Block for the block header list. This does not retain the Block so you can pass an Block into this while releasing control from the calling function.
self The BlockHeaders object address The Block to take. true if the block header was taken successfully or false on error.
References TRUE.
Referenced by addBlockHeaderToBlockHeaderList.