Block.c
Block createNewBlock(void(*onErrorReceived)(Error error, char *,...))
Creates a new Block.
Block
References deleteBlock, Object::destroy, ERROR_OUT_OF_MEMORY, getObject, initBlock.
Block createNewBlockFromByteArray(ByteArray *info, void(*onErrorReceived)(Error error, char *,...))
Create a new Block from a given ByteArray data.
Creates a new Block. info Block data Block
References deleteBlock, Object::destroy, ERROR_OUT_OF_MEMORY, getObject, initBlockFromByteArray.
Referenced by deserializeBlockHeaders.
Block * createNewBlockFromOriginalBlock(void(*onErrorReceived)(Error error, char *,...))
Create a new Block from a default Block.
Block
References deleteBlock, Object::destroy, ERROR_OUT_OF_MEMORY, getObject, initBlockWithGenesisBlockInfo.
Block * getBlock(void *block)
get a block Object
Gets a Block from another object. Use this to avoid casts. block Block self The object to obtain the Block from. The Block object.
int initBlock(Block *self, void(*onErrorReceived)(Error error, char *,...))
Initialize the Block from.
self TRUE or FALSE
References FALSE, getMessage, initializeMessageFromObject, TRUE.
Referenced by createNewBlock.
int initBlockFromByteArray(Block *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initialize the Block from ByteArray.
Initializes a Block object from serialized data. self data TRUE or FALSE self The Block object to initialize data The serialized data. true on success, false on failure.
References FALSE, getMessage, initializeMessageFromByteArrayData, TRUE.
Referenced by createNewBlockFromByteArray.
int initBlockWithGenesisBlockInfo(Block *self, void(*onErrorReceived)(Error error, char *,...))
References createNewByteArrayUsingDataCopy, decrementReferenceCount, deserializeBlock, FALSE, getMessage, initializeMessageFromByteArrayData, TRUE.
Referenced by createNewBlockFromOriginalBlock.
void deleteBlock(void *selfCopy)
Destroy the Block.
Frees a Block object. selfCopy self The Block object to free.
References decrementReferenceCount, destroyMessage, getObject.
Referenced by createNewBlock, createNewBlockFromByteArray, createNewBlockFromOriginalBlock.
void calculateBlockHash(Block *self, uint8_t *hash)
Calculate the hash for a Block.
Calculates the hash for a block. self hash self The Block object. This should be serialized. The hash for the block to be set. This should be 32 bytes long.
References getByteArrayData, getMessage, Sha256.
Referenced by getBlockHash.
uint32_t calculateBlockLength(Block *self, int transactions)
Calculate the length of Block that is needed to serialize the object.
Calculates the length needed to serialize the object. self transactions blocklength self The Block object. transactions If true, the full block, if not true just the header. The length read on success, 0 on failure.
References calculateTransactionLength, getSizeOfVarLenInt.
uint32_t deserializeBlock(Block *self, int transactions)
Deserialize the Block.
Deserializes a Block so that it can be used as an object. self transactions 0 self The Block object transactions If true deserialize transactions. If false there do not deserialize for transactions. The length read on success, 0 on failure.
References Message::bytes, deserializeWithOnlyHeaders, deserializeWithTransactions, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, getByteArraySubsectionReference, getByteFromByteArray, getMessage, ByteArray::length, Message::onErrorReceived, readInt32AsLittleEndianFromByteArray.
Referenced by deserializeBlockHeaders, initBlockWithGenesisBlockInfo.
uint32_t deserializeWithTransactions(Block *self, ByteArray *bytes)
Deserialize With Transaction.
self bytes 0 @ breif deserialize Block with transactions @ param self The Block object @ param bytes ByteArray object @ The length read on success, o on failure.
References createNewTransactionFromByteArray, decodeVarLenInt, decrementReferenceCount, deserializeTransaction, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_OUT_OF_MEMORY, getByteArraySubsectionReference, getMessage, ByteArray::length, Message::onErrorReceived, VarLenInt::storageSize, VarLenInt::value.
Referenced by deserializeBlock.
uint32_t deserializeWithOnlyHeaders(Block *self, uint8_t firstByte, ByteArray *bytes)
Deserialize With Transaction.
self firstByte bytes 0 @ breif deserialize Block only with headers @ param self The Block object @ param firstByte uint8_t @ param bytes ByteArray object @ The length read on success, o on failure.
References decodeVarLenInt, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, getByteFromByteArray, getMessage, ByteArray::length, Message::onErrorReceived, VarLenInt::value.
Referenced by deserializeBlock.
uint8_t * getBlockHash(Block *self)
Get the hash of the Block.
Retrieves or calculates the hash for a block. Hashes taken from this function are cached. self hash self The Block object. This should be serialised. The hash for the block. This is a 32 byte long, double SHA-256 hash and is a pointer to the hash field in the block.
References calculateBlockHash.
uint32_t serializeBlock(Block *self, int transactions)
Serializes a Block to the byte data.
self The Block object transactions If true serialize transactions. If false there do not serialize for transactions. The length read on success, 0 on failure.
References Message::bytes, createVarLenIntFromUInt64, dealWithSerializationHeader, dealWithSerializationTran, encodeVarLenInt, ERROR_MESSAGE_SERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_NULL_BYTES, getMessage, ByteArray::length, Message::onErrorReceived, VarLenInt::storageSize.
Referenced by serializeBlockHeaders.
void dealWithSerializationHeader(Block *self, ByteArray *bytes)
To deal with the header issue for serializeBlock.
self The Block object bytes The ByteArray
References changeByteArrayDataReference, copyByteArrayToByteArray, writeInt32AsLittleEndianIntoByteArray.
Referenced by serializeBlock.
uint32_t dealWithSerializationTran(Block *self, ByteArray *bytes, uint32_t cursor, int transactions)
dealt with the transaction issue for serializeBlock. self The Block object bytes The ByteArray cursor The initial cursor The cursor
References Message::bytes, ERROR_INIT_FAIL, ERROR_MESSAGE_SERIALISATION_BAD_BYTES, getByteArraySubsectionReference, getMessage, ByteArray::length, Message::onErrorReceived, serializeTransaction, setByteInByteArray.
Referenced by serializeBlock.