ByteArray.c
void copyByteArrayToByteArray(ByteArray *self, uint32_t writeOffset, ByteArray *source)
copy a ByteArray To another ByteArray
Copies another byte array to this byte array. self writeOffset source
References SharedData::data, ByteArray::length, ByteArray::offset, ByteArray::sharedData.
Referenced by dealWithSerializationHeader, getTransactionInputHashForVerification, serializeChainDescriptor, serializeGetBlocks, serializeInventoryVector, serializeTransactionInput, serializeTransactionOutput.
int isNullByteArray(ByteArray *self)
Checks if the byte array is null or not.
Determines if a ByteArray is null. self TRUE/FALSE
References FALSE, TRUE.
Referenced by isCoinBase.
ByteArray* getByteArray(void *self)
Gets a ByteArray from another object. Use this to avoid casts.
self The object to obtain the ByteArray from. The ByteArray object.
Referenced by FreeVersionChecksumBytes, getTransactionInputHashForVerification, InitVersionChecksumBytesFromBytes, InitVersionChecksumBytesFromString, serializeTransactionInput, serializeTransactionOutput, VersionChecksumBytesGetVersion.
uint8_t* getByteArrayData(ByteArray *self)
Get a pointer to the underlying data starting at self->offset.
self The ByteArray object. The pointer
Referenced by BuildMerkleTree, calculateBlockHash, calculateTransactionHash, compareByteArrays, executeScript, getTransactionInputHashForVerification.
uint8_t getByteFromByteArray(ByteArray *self, uint32_t index)
gets Byte from ByteArray
Get a byte from the ByteArray object. A byte will be returned from self->offset+index in the underlying data. self self index uint8_t
Referenced by decodeVarLenInt, deserializeBlock, deserializeTransactionOutput, deserializeWithOnlyHeaders, executeScript, isP2SHScript, VersionChecksumBytesGetVersion.
ByteArray * getByteArraySubsectionReference(ByteArray *refByteArray, uint32_t offset, uint32_t length)
gets ByteArray Subsection Reference
References a subsection of a ByteArray. refByteArray offset length NULL
References Object::destroy, destroyByteArray, ERROR_OUT_OF_MEMORY, getObject, initializeByteArraySubsectionReference, ByteArray::onErrorReceived.
Referenced by createNewScriptFromReference, dealWithSerializationTran, deserializeBlock, deserializeBlockHeaders, deserializeChainDescriptor, deserializeGetBlocks, deserializeInventory, deserializeInventoryVector, deserializeTransaction, deserializeTransactionInput, deserializeWithTransactions, serialiseInventory, serializeBlockHeaders, serializeGetBlocks, serializeTransaction.
int initializeByteArraySubsectionReference(ByteArray *self, ByteArray *refByteArray, uint32_t offset, uint32_t length)
initializes ByteArray Subsection Reference
Initialises a reference ByteArray to a subsection of an ByteArray. self refByteArray offset length TRUE/FALSE
References FALSE, getObject, ByteArray::length, ByteArray::offset, ByteArray::onErrorReceived, SharedData::referenceCount, Object::referenceCount, ByteArray::sharedData, TRUE.
Referenced by getByteArraySubsectionReference.
void destroyByteArray(void *self)
destorys byte array
Destroys a ByteArray object. self
References destroyObject, getObject, releaseByteArraySharedDataReference.
Referenced by createNewByteArrayFromData, createNewByteArrayOfSize, createNewByteArrayUsingDataCopy, FreeVersionChecksumBytes, getByteArraySubsectionReference.
void releaseByteArraySharedDataReference(ByteArray *self)
release Byte Array SharedData Reference
Releases a reference to shared byte data and frees the data if necessary. self
Referenced by changeByteArrayDataReference, destroyByteArray.
uint16_t readInt16AsLittleEndianFromByteArray(ByteArray *self, uint32_t offset)
read an int 16 As little Endian from ByteArray
Reads a 16 bit integer from a ByteArray as little-endian. self offset result
Referenced by decodeVarLenInt, executeScript.
uint32_t readInt32AsLittleEndianFromByteArray(ByteArray *self, uint32_t offset)
read an int 32 As little Endian from ByteArray
Reads a 32 bit integer from a ByteArray as little-endian. self offset result
Referenced by decodeVarLenInt, deserializeBlock, deserializeGetBlocks, deserializeInventoryVector, deserializeTransaction, deserializeTransactionInput, executeScript.
uint32_t readInt64AsLittleEndianFromByteArray(ByteArray *self, uint32_t offset)
read an int 64 As little Endian from ByteArray
Reads a 64 bit integer from the ByteArray as little-endian. self offset result
Referenced by decodeVarLenInt, deserializePingPongMessage, deserializeTransactionOutput.
void setByteInByteArray(ByteArray *self, uint32_t index, uint8_t byte)
sets Byte In ByteArray
Set a byte into the array. This will be set at self->offset+index in the underlying data.sets Bytes In ByteArray self index byte self index bytes length
Referenced by dealWithSerializationTran, encodeVarLenInt, serializeGetBlocks.
void setBytesInByteArray(ByteArray *self, uint32_t index, uint8_t *bytes, uint32_t length)
Copies a length of bytes into the array. This will be set at self->offset+index in the underlying data.
self The ByteArray object. index The index in the array to start writing. bytes The pointer to the bytes to be copied. length The number of bytes to copy.
void writeInt16AsLittleEndianIntoByteArray(ByteArray *self, uint32_t offset, uint16_t integer)
writes Integer_16 as Little-Endian Into ByteArray
Writes a 16 bit integer to a ByteArray as little-endian. self offset integer
Referenced by encodeVarLenInt.
void writeInt32AsLittleEndianIntoByteArray(ByteArray *self, uint32_t offset, uint32_t integer)
writes Integer_32 as Little-Endian Into ByteArray
Writes a 32 bit integer to a ByteArray as little-endian. self offset integer
Referenced by dealWithSerializationHeader, encodeVarLenInt, getTransactionInputHashForVerification, serializeInventoryVector, serializeTransaction, serializeTransactionInput.
void writeInt64AsLittleEndianIntoByteArray(ByteArray *self, uint32_t offset, uint64_t integer)
writes Integer_64 as Little-Endian Into ByteArray
Writes a 64 bit integer to a ByteArray as little-endian. self offset integer
Referenced by encodeVarLenInt, getTransactionInputHashForVerification, serializePingPongMessage, serializeTransactionOutput.
void changeByteArrayDataReference(ByteArray *self, ByteArray *ref, uint32_t offset)
changes ByteArray Data's Reference
Changes the reference of this ByteArray object to reference the underlying data of another ByteArray. Useful for moving byte data into single underlying data by copying the data into a larger ByteArray and then changing the reference to this new larger ByteArray. self ref offset
References ByteArray::offset, SharedData::referenceCount, releaseByteArraySharedDataReference, ByteArray::sharedData.
Referenced by dealWithSerializationHeader, serializeChainDescriptor, serializeGetBlocks, serializeInventoryVector, serializeTransactionInput, serializeTransactionOutput.
ByteArray * createNewByteArrayOfSize(uint32_t size, void(*onErrorReceived)(Error error, char *,...))
createNewByteArrayOfSize
Creates an empty ByteArray object. self ref offset
References Object::destroy, destroyByteArray, ERROR_OUT_OF_MEMORY, getObject, initByteArrayOfSize.
Referenced by getTransactionInputHashForVerification.
Compare compareByteArrays(ByteArray *first, ByteArray *second)
initByteArrayOfSize
Compares a ByteArray to another ByteArray and returns with a Compare value. self second memcmp
References COMPARE_LESS_THAN, COMPARE_MORE_THAN, getByteArrayData, ByteArray::length.
int initByteArrayOfSize(ByteArray *self, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
initByteArrayOfSize
Initialises an empty ByteArray object. self ref offset
References ERROR_OUT_OF_MEMORY, FALSE, getObject, Object::referenceCount, TRUE.
Referenced by createNewByteArrayOfSize.
ByteArray * createNewByteArrayFromData(uint8_t *data, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
createNewByteArrayFromData
Creates a new ByteArray using data. self ref offset NULL
References Object::destroy, destroyByteArray, ERROR_OUT_OF_MEMORY, getObject, initNewByteArrayFromData.
Referenced by createNewScriptStackFromData, executeScript.
ByteArray * createNewByteArrayUsingDataCopy(uint8_t *data, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
createNewByteArrayUsingDataCopy
Creates a new ByteArray using data which is copied. self ref offset NULL
References Object::destroy, destroyByteArray, ERROR_OUT_OF_MEMORY, getObject, initNewByteArrayUsingDataCopy.
Referenced by createNewScriptStackUsingCopyOfData, initBlockWithGenesisBlockInfo.
int initNewByteArrayUsingDataCopy(ByteArray *self, uint8_t *data, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
initNewByteArrayUsingDataCopy
Creates a new ByteArray using data which is copied. self data size TRUE/FALSE
References ERROR_OUT_OF_MEMORY, FALSE, getObject, Object::referenceCount, TRUE.
Referenced by createNewByteArrayUsingDataCopy.
int initNewByteArrayFromData(ByteArray *self, uint8_t *data, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
createNewByteArrayUsingDataCopy
Creates a new ByteArray using data. self ref offset TRUE/FALSE
References ERROR_OUT_OF_MEMORY, FALSE, getObject, Object::referenceCount, TRUE.
Referenced by createNewByteArrayFromData, InitVersionChecksumBytesFromBytes, InitVersionChecksumBytesFromString.
void reverseBytes(ByteArray *self)
Reverses the bytes.
self The ByteArray object to reverse
Referenced by InitVersionChecksumBytesFromString.