ByteArray.h
ByteArray* createNewByteArrayFromString(char *string, int terminator, void(*onErrorReceived)(Error error, char *,...))
Creates a ByteArray object from a C string. The termination character is not included in the new ByteArray.
string The string to put into a ByteArray. terminator If true, include the termination character. onErrorReceived Engine for errors. A new ByteArray object.
ByteArray* createNewByteArrayOfSize(uint32_t size, void(*onErrorReceived)(Error error, char *,...))
Creates an empty ByteArray object.
size Size in bytes for the new array. onErrorReceived Engine for errors. An empty ByteArray object. Creates an empty ByteArray object. self ref offset
References Object::destroy, destroyByteArray, ERROR_OUT_OF_MEMORY, getObject, initByteArrayOfSize.
Referenced by getTransactionInputHashForVerification.
ByteArray* createNewByteArrayFromData(uint8_t *data, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
Creates a new ByteArray using data.
data The data. This should be dynamically allocated. The new ByteArray object will take care of it's memory management so do not free this data once passed into this constructor. size Size in bytes for the new array. onErrorReceived Engine for errors. The new ByteArray object. Creates a new ByteArray using data. self ref offset NULL
References Object::destroy, destroyByteArray, ERROR_OUT_OF_MEMORY, getObject, initNewByteArrayFromData.
Referenced by createNewScriptStackFromData, executeScript.
ByteArray* createNewByteArrayUsingDataCopy(uint8_t *data, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
Creates a new ByteArray using data which is copied.
data The data. This data is copied. size Size in bytes for the new array. onErrorReceived Engine for errors. The new ByteArray object. Creates a new ByteArray using data which is copied. self ref offset NULL
References Object::destroy, destroyByteArray, ERROR_OUT_OF_MEMORY, getObject, initNewByteArrayUsingDataCopy.
Referenced by createNewScriptStackUsingCopyOfData, initBlockWithGenesisBlockInfo.
ByteArray* getByteArray(void *self)
Gets a ByteArray from another object. Use this to avoid casts.
self The object to obtain the ByteArray from. The ByteArray object.
Referenced by FreeVersionChecksumBytes, getTransactionInputHashForVerification, InitVersionChecksumBytesFromBytes, InitVersionChecksumBytesFromString, serializeTransactionInput, serializeTransactionOutput, VersionChecksumBytesGetVersion.
int initByteArrayFromString(ByteArray *self, char *string, int terminator, void(*onErrorReceived)(Error error, char *,...))
Initialises a ByteArray object from a C string. The termination character is not included in the new ByteArray.
self The ByteArray object to initialise string The string to put into a ByteArray. terminator If tru, include the termination character. onErrorReceived Engine for errors. true on success, false on failure.
int initByteArrayOfSize(ByteArray *self, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
Initialises an empty ByteArray object.
self The ByteArray object to initialise size Size in bytes for the new array. onErrorReceived Engine for errors. true on success, false on failure. Initialises an empty ByteArray object. self ref offset
References ERROR_OUT_OF_MEMORY, FALSE, getObject, Object::referenceCount, TRUE.
Referenced by createNewByteArrayOfSize.
int initNewByteArrayFromData(ByteArray *self, uint8_t *data, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
Creates a new ByteArray using data.
self The ByteArray object to initialise data The data. This should be dynamically allocated. The new ByteArray object will take care of it's memory management so do not free this data once passed into this constructor. size Size in bytes for the new array. onErrorReceived Engine for errors. true on success, false on failure. Creates a new ByteArray using data. self ref offset TRUE/FALSE
References ERROR_OUT_OF_MEMORY, FALSE, getObject, Object::referenceCount, TRUE.
Referenced by createNewByteArrayFromData, InitVersionChecksumBytesFromBytes, InitVersionChecksumBytesFromString.
int initNewByteArrayUsingDataCopy(ByteArray *self, uint8_t *data, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
Creates a new ByteArray using data which is copied.
self The ByteArray object to initialise data The data. This data is copied. size Size in bytes for the new array. onErrorReceived Engine for errors. true on success, false on failure. Creates a new ByteArray using data which is copied. self data size TRUE/FALSE
References ERROR_OUT_OF_MEMORY, FALSE, getObject, Object::referenceCount, TRUE.
Referenced by createNewByteArrayUsingDataCopy.
int initializeByteArraySubsectionReference(ByteArray *self, ByteArray *refByteArray, uint32_t offset, uint32_t length)
Initialises a reference ByteArray to a subsection of an ByteArray.
self The ByteArray object to initialise. refByteArray The ByteArray object to reference. offset The offset to the start of the reference. length The length of the reference. If 0 the length is set to be the same as the reference ByteArray. true on success, false on failure. Initialises a reference ByteArray to a subsection of an ByteArray. self refByteArray offset length TRUE/FALSE
References FALSE, getObject, ByteArray::length, ByteArray::offset, ByteArray::onErrorReceived, SharedData::referenceCount, Object::referenceCount, ByteArray::sharedData, TRUE.
Referenced by getByteArraySubsectionReference.
void destroyByteArray(void *self)
Destroys a ByteArray object.
self The ByteArray object to destroy. Destroys a ByteArray object. self
References destroyObject, getObject, releaseByteArraySharedDataReference.
Referenced by createNewByteArrayFromData, createNewByteArrayOfSize, createNewByteArrayUsingDataCopy, FreeVersionChecksumBytes, getByteArraySubsectionReference.
void releaseByteArraySharedDataReference(ByteArray *self)
Releases a reference to shared byte data and frees the data if necessary.
self The ByteArray object with the SharedData Releases a reference to shared byte data and frees the data if necessary. self
Referenced by changeByteArrayDataReference, destroyByteArray.
uint16_t readInt16AsLittleEndianFromByteArray(ByteArray *self, uint32_t offset)
Reads a 16 bit integer from a ByteArray as little-endian.
self The ByteArray object offset Offset to where to start the read A 16 bit integer. This can be cast to a signed integer if reading integer as a signed value. Reads a 16 bit integer from a ByteArray as little-endian. self offset result
Referenced by decodeVarLenInt, executeScript.
uint32_t readInt32AsLittleEndianFromByteArray(ByteArray *self, uint32_t offset)
Reads a 32 bit integer from a ByteArray as little-endian.
self The ByteArray object offset Offset to where to start the read A 32 bit integer. This can be cast to a signed integer if reading integer as a signed value Reads a 32 bit integer from a ByteArray as little-endian. self offset result
Referenced by decodeVarLenInt, deserializeBlock, deserializeGetBlocks, deserializeInventoryVector, deserializeTransaction, deserializeTransactionInput, executeScript.
uint64_t readInt64AsLittleEndianFromByteArray(ByteArray *self, uint32_t offset)
Reads a 64 bit integer from the ByteArray as little-endian.
self The ByteArray object offset Offset to where to start the read A 64 bit integer. This can be cast to a signed integer if reading integer as a signed value Reads a 64 bit integer from the ByteArray as little-endian. self offset result
Referenced by decodeVarLenInt, deserializePingPongMessage, deserializeTransactionOutput.
Compare compareByteArrays(ByteArray *self, ByteArray *second)
Compares a ByteArray to another ByteArray and returns with a Compare value.
self The ByteArray object to compare second Another ByteArray object to compare with If the lengths are different, _COMPARE_MORE_THAN if "self" if longer, else _COMPARE_LESS_THAN. If the bytes are equal _COMPARE_EQUAL, else _COMPARE_MORE_THAN if the first different byte if higher in "self", otherwise _COMPARE_LESS_THAN. The return value can be treated like the return value to memcmp. Compares a ByteArray to another ByteArray and returns with a Compare value. self second memcmp
References COMPARE_LESS_THAN, COMPARE_MORE_THAN, getByteArrayData, ByteArray::length.
ByteArray* copyByteArray(ByteArray *self)
Copies a ByteArray.
self The ByteArray object to copy The new ByteArray.
void copyByteArrayToByteArray(ByteArray *self, uint32_t writeOffset, ByteArray *source)
Copies another byte array to this byte array.
self The ByteArray object to copy to. writeOffset The offset to begin writing to in self. source The ByteArray to copy from. Copies another byte array to this byte array. self writeOffset source
References SharedData::data, ByteArray::length, ByteArray::offset, ByteArray::sharedData.
Referenced by dealWithSerializationHeader, getTransactionInputHashForVerification, serializeChainDescriptor, serializeGetBlocks, serializeInventoryVector, serializeTransactionInput, serializeTransactionOutput.
void copySubsectionOfByteArrayToByteArray(ByteArray *self, uint32_t writeOffset, ByteArray *source, uint32_t readOffset, uint32_t length)
Copies a section of another byte array to this byte array.
self The ByteArray object. writeOffset The offset to begin writing source The ByteArray to copy from. readOffset The offset of the source array to begin reading. length The length to copy.
ByteArray* createNewByteArrayFromSubsection(ByteArray *self, uint32_t offset, uint32_t length)
Copies a subsection of a ByteArray.
self The ByteArray object to copy from. offset The offset to the start of the copy. length The length of the copy. The new ByteArray.
ByteArray* getByteArraySubsectionReference(ByteArray *self, uint32_t offset, uint32_t length)
References a subsection of a ByteArray.
self The ByteArray object to reference. offset The offset to the start of the reference. length The length of the reference. The new ByteArray. References a subsection of a ByteArray. refByteArray offset length NULL
References Object::destroy, destroyByteArray, ERROR_OUT_OF_MEMORY, getObject, initializeByteArraySubsectionReference, ByteArray::onErrorReceived.
Referenced by createNewScriptFromReference, dealWithSerializationTran, deserializeBlock, deserializeBlockHeaders, deserializeChainDescriptor, deserializeGetBlocks, deserializeInventory, deserializeInventoryVector, deserializeTransaction, deserializeTransactionInput, deserializeWithTransactions, serialiseInventory, serializeBlockHeaders, serializeGetBlocks, serializeTransaction.
uint8_t getByteFromByteArray(ByteArray *self, uint32_t index)
Get a byte from the ByteArray object. A byte will be returned from self->offset+index in the underlying data.
self The ByteArray object. index The index in the array to get the byte from The byte Get a byte from the ByteArray object. A byte will be returned from self->offset+index in the underlying data. self self index uint8_t
Referenced by decodeVarLenInt, deserializeBlock, deserializeTransactionOutput, deserializeWithOnlyHeaders, executeScript, isP2SHScript, VersionChecksumBytesGetVersion.
uint8_t* getByteArrayData(ByteArray *self)
Get a pointer to the underlying data starting at self->offset.
self The ByteArray object. The pointer
Referenced by BuildMerkleTree, calculateBlockHash, calculateTransactionHash, compareByteArrays, executeScript, getTransactionInputHashForVerification.
uint8_t getLastByteFromByteArray(ByteArray *self)
Get the last byte from the ByteArray object. A byte will be returned from self->offset+self->length in the underlying data.
self The ByteArray object. The last byte
int isNullByteArray(ByteArray *self)
Determines if a ByteArray is null.
self The ByteArray object. true if all bytes are zero, else false. Determines if a ByteArray is null. self TRUE/FALSE
References FALSE, TRUE.
Referenced by isCoinBase.
void setByteInByteArray(ByteArray *self, uint32_t index, uint8_t byte)
Set a byte into the array. This will be set at self->offset+index in the underlying data.
self The ByteArray object. index The index in the array to set the byte byte The byte to be set. Set a byte into the array. This will be set at self->offset+index in the underlying data.sets Bytes In ByteArray self index byte self index bytes length
Referenced by dealWithSerializationTran, encodeVarLenInt, serializeGetBlocks.
void setBytesInByteArray(ByteArray *self, uint32_t index, uint8_t *bytes, uint32_t length)
Copies a length of bytes into the array. This will be set at self->offset+index in the underlying data.
self The ByteArray object. index The index in the array to start writing. bytes The pointer to the bytes to be copied. length The number of bytes to copy.
void writeInt16AsLittleEndianIntoByteArray(ByteArray *self, uint32_t offset, uint16_t integer)
Writes a 16 bit integer to a ByteArray as little-endian.
self The ByteArray object offset Offset to where to start the write integer The 16 bit integer to set. The argument is an unsigned integer but signed or unsigned integers are OK to pass. Writes a 16 bit integer to a ByteArray as little-endian. self offset integer
Referenced by encodeVarLenInt.
void writeInt32AsLittleEndianIntoByteArray(ByteArray *self, uint32_t offset, uint32_t integer)
Writes a 32 bit integer to a ByteArray as little-endian.
self The ByteArray object offset Offset to where to start the write integer The 32 bit integer to set. The argument is an unsigned integer but signed or unsigned integers are OK to pass. Writes a 32 bit integer to a ByteArray as little-endian. self offset integer
Referenced by dealWithSerializationHeader, encodeVarLenInt, getTransactionInputHashForVerification, serializeInventoryVector, serializeTransaction, serializeTransactionInput.
void writeInt64AsLittleEndianIntoByteArray(ByteArray *self, uint32_t offset, uint64_t integer)
Writes a 64 bit integer to a ByteArray as little-endian.
self The ByteArray object offset Offset to where to start the write integer The 64 bit integer to set. The argument is an unsigned integer but signed or unsigned integers are OK to pass. Writes a 64 bit integer to a ByteArray as little-endian. self offset integer
Referenced by encodeVarLenInt, getTransactionInputHashForVerification, serializePingPongMessage, serializeTransactionOutput.
void reverseBytes(ByteArray *self)
Reverses the bytes.
self The ByteArray object to reverse
Referenced by InitVersionChecksumBytesFromString.
void changeByteArrayDataReference(ByteArray *self, ByteArray *ref, uint32_t offset)
Changes the reference of this ByteArray object to reference the underlying data of another ByteArray. Useful for moving byte data into single underlying data by copying the data into a larger ByteArray and then changing the reference to this new larger ByteArray.
self The ByteArray object to change the reference for. ref The ByteArray object to get the reference from. offset The offset to start the reference. The new ByteArray. Changes the reference of this ByteArray object to reference the underlying data of another ByteArray. Useful for moving byte data into single underlying data by copying the data into a larger ByteArray and then changing the reference to this new larger ByteArray. self ref offset
References ByteArray::offset, SharedData::referenceCount, releaseByteArraySharedDataReference, ByteArray::sharedData.
Referenced by dealWithSerializationHeader, serializeChainDescriptor, serializeGetBlocks, serializeInventoryVector, serializeTransactionInput, serializeTransactionOutput.