ChainDescriptor.h
ChainDescriptor* newChainDescriptor(void(*onErrorReceived)(Error error, char *,...))
Creates a new ChainDescriptor object.
A new ChainDescriptor object.
References Object::destroy, ERROR_OUT_OF_MEMORY, freeChainDescriptor, getObject, initChainDescriptor.
ChainDescriptor* newChainDescriptorFromData(ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new ChainDescriptor object from serialized data.
data Serialized ChainDescriptor data. A new ChainDescriptor object.
References Object::destroy, ERROR_OUT_OF_MEMORY, freeChainDescriptor, getObject, initChainDescriptorFromData.
Referenced by deserializeGetBlocks.
ChainDescriptor* getChainDescriptor(void *self)
Gets a ChainDescriptor from another object. Use this to avoid casts.
self The object to obtain the ChainDescriptor from. The ChainDescriptor object.
int initChainDescriptor(ChainDescriptor *self, void(*onErrorReceived)(Error error, char *,...))
Initializes a ChainDescriptor object.
self The ChainDescriptor object to initialize true on success, false on failure.
References FALSE, getMessage, initializeMessageFromObject, TRUE.
Referenced by newChainDescriptor.
int initChainDescriptorFromData(ChainDescriptor *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initializes a ChainDescriptor object from serialized data.
self The ChainDescriptor object to initialize data The serialized data. true on success, false on failure.
References FALSE, getMessage, initializeMessageFromByteArrayData, TRUE.
Referenced by newChainDescriptorFromData.
void freeChainDescriptor(void *self)
Frees a ChainDescriptor object.
self The ChainDescriptor object to free.
References destroyMessage, destroyObject.
Referenced by newChainDescriptor, newChainDescriptorFromData.
int addHashToChainDescriptor(ChainDescriptor *self, ByteArray *hash)
Adds a hash to the ChainDescriptor onto the end.
self The ChainDescriptor object hash The hash to add. true if the hash was added successfully, false on error.
References incrementReferenceCount, takeHashForChainDescriptor.
uint16_t deserializeChainDescriptor(ChainDescriptor *self)
Deserializes a ChainDescriptor so that it can be used as an object.
self The ChainDescriptor object The length read on success, 0 on failure.
References Message::bytes, decodeVarLenInt, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, ERROR_OUT_OF_MEMORY, getByteArraySubsectionReference, getMessage, ByteArray::length, Message::onErrorReceived, VarLenInt::storageSize, VarLenInt::value.
Referenced by deserializeGetBlocks.
uint16_t serializeChainDescriptor(ChainDescriptor *self)
Serializes a ChainDescriptor to the byte data.
self The ChainDescriptor object The length written on success, 0 on failure.
References Message::bytes, changeByteArrayDataReference, copyByteArrayToByteArray, createVarLenIntFromUInt64, encodeVarLenInt, ERROR_MESSAGE_SERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_NULL_BYTES, getMessage, ByteArray::length, Message::onErrorReceived, VarLenInt::storageSize.
Referenced by serializeGetBlocks.
int takeHashForChainDescriptor(ChainDescriptor *self, ByteArray *hash)
Takes a hash for the ChainDescriptor and puts it on the end. The hash is not retained so the calling function is releasing control.
self The ChainDescriptor object hash The hash to take. true if the hash was taken successfully, false on error.
References FALSE, TRUE.
Referenced by addHashToChainDescriptor.