Crypt.h
void Sha256(uint8_t *data, uint16_t length, uint8_t *output)
SHA-256 cryptographic hash function.
data A pointer to the byte data to hash. length The length of the data to hash. output A pointer to hold a 32-byte hash.
Referenced by BuildMerkleTree, calculateBlockHash, calculateTransactionHash, executeScript, GetCheckSum, getTransactionInputHashForVerification, InitAddressFromRIPEMD160Hash.
void Ripemd160(uint8_t *data, uint16_t length, uint8_t *output)
RIPEMD-160 cryptographic hash function.
data A pointer to the byte data to hash. length The length of the data to hash. output A pointer to hold a 20-byte hash.
Referenced by executeScript.
void Sha160(uint8_t *data, uint16_t length, uint8_t *output)
SHA-1 cryptographic hash function.
data A pointer to the byte data to hash. length The length of the data to hash. output A pointer to hold a 10-byte hash.
Referenced by executeScript.
int ECDSAVerify(uint8_t *signature, uint8_t signatureLen, uint8_t *hash, const uint8_t *pubKey, uint8_t keyLen)
Verifies an ECDSA signature. This function must stick to the cryptography requirements in OpenSSL version 1.0.0 or any other compatible version. There may be compatibility problems when using libraries or code other than OpenSSL since OpenSSL does not adhere fully to the SEC1 ECDSA standards. This could cause security problems in your code. If in doubt, stick to OpenSSL.
signature BER encoded signature bytes. signatureLen The length of the signature bytes. hash A 32 byte hash for checking the signature against. pubKey Public key bytes to check this signature with. keyLen The length of the public key bytes. true if the signature is valid and false if invalid.
Referenced by executeScript.