Dependencies.h
void Sha256(uint8_t *data, uint16_t length, uint8_t *output)
SHA-256 cryptographic hash function.
data A pointer to the byte data to hash. length The length of the data to hash. output A pointer to hold a 32-byte hash.
Referenced by calculateBlockHash, calculateTransactionHash, getTransactionInputHashForVerification.
void Ripemd160(uint8_t *data, uint16_t length, uint8_t *output)
RIPEMD-160 cryptographic hash function.
data A pointer to the byte data to hash. length The length of the data to hash. output A pointer to hold a 20-byte hash.
void Sha160(uint8_t *data, uint16_t length, uint8_t *output)
SHA-1 cryptographic hash function.
data A pointer to the byte data to hash. length The length of the data to hash. output A pointer to hold a 10-byte hash.
int EcdsaVerify(uint8_t *signature, uint8_t sigLen, uint8_t *hash, const uint8_t *pubKey, uint8_t keyLen)
Verifies an ECDSA signature. This function must stick to the cryptography requirements in OpenSSL version 1.0.0 or any other compatible version. There may be compatibility problems when using libraries or code other than OpenSSL since OpenSSL does not adhere fully to the SEC1 ECDSA standards. This could cause security problems in your code. If in doubt, stick to OpenSSL.
signature BER encoded signature bytes. sigLen The length of the signature bytes. hash A 32 byte hash for checking the signature against. pubKey Public key bytes to check this signature with. keyLen The length of the public key bytes. true if the signature is valid and false if invalid.
SocketReturn NewSocket(uint64_t *socketID, int IPv6)
Creates a new TCP/IP socket. The socket should use a non-blocking mode.
socketID Pointer to uint64_t. Can be pointer value. IPv6 true if the socket is used to connect to the IPv6 network. _SOCKET_OK if the socket was successfully created, _SOCKET_NO_SUPPORT and _SOCKET_BAD if the socket could not be created for any other reason.
int SocketBind(uint64_t *socketID, int IPv6, uint16_t port)
int SocketConnect(uint64_t socketID, uint8_t *IP, int IPv6, uint16_t port)
Begin connecting to an external host with a socket. This should be non-blocking.
socketID The socket id IP 16 bytes for an IPv6 address to connect to. IPv6 True if IP address is for the IPv6 network. A IPv6 address can represent addresses for IPv4 too. To avoid the need to detect this, a intean can be used. port Port to connect to. true if the function was sucessful and false otherwise.
int SocketListen(uint64_t socketID, uint16_t maxConnections)
Begin listening for incomming connections on a bound socket. This should be non-blocking.
socketID The socket id maxConnections The maximum incomming connections to allow. true if function was sucessful and false otherwise.
int SocketAccept(uint64_t socketID, uint64_t *connectionSocketID)
Accepts an incomming IPv4 connection on a bound socket. This should be non-blocking.
socketID The socket id connectionSocketID A socket id for a new socket for the connection. true if function was sucessful and false otherwise.
int NewEventLoop(uint64_t *loopID, void(*onError)(void *), void(*onDidTimeout)(void *, void *, TimeOutType), void *communicator)
Starts a event loop for socket onErrorReceived on a seperate thread. Access to the loop id should be thread safe.
loopID A uint64_t storing an integer or pointer representation of the new event loop. onError If the event loop fails during execution of the thread, this function should be called. onDidTimeout The function to call for timeout onErrorReceived. The second argument is for the peer given by onErrorReceived. The third is for the timeout type. For receiving data, the timeout should be _TIMEOUT_RECEIVE. The NetworkCommunicator will determine if it should be changed to _TIMEOUT_RESPONSE. communicator A NetworkCommunicator to pass to all event functions (first parameter), including "onError" and "onDidTimeout" true on success, false on failure.
int SocketCanAcceptEvent(uint64_t *eventID, uint64_t loopID, uint64_t socketID, void(*onCanAccept)(void *, uint64_t))
Creates an event where a listening socket is available for accepting a connection. The event should be persistent and not issue timeouts.
loopID The loop id for socket onErrorReceived. socketID The socket id onCanAccept The function to call for the event. Accepts "onEventArg" and the socket ID. true on success, false on failure.
int SocketDidConnectEvent(uint64_t *eventID, uint64_t loopID, uint64_t socketID, void(*onDidConnect)(void *, void *), void *peer)
Sets a function pointer for the event where a socket has connected. The event only needs to fire once on the successful connection or timeout.
loopID The loop id for socket onErrorReceived. socketID The socket id onDidConnect The function to call for the event. peer The peer to send to the "onDidConnect" or "onDidTimeout" function. true on success, false on failure.
int SocketCanSendEvent(uint64_t *eventID, uint64_t loopID, uint64_t socketID, void(*onCanSend)(void *, void *), void *peer)
Sets a function pointer for the event where a socket is available for sending data. This should be persistent.
loopID The loop id for socket onErrorReceived. socketID The socket id onCanSend The function to call for the event. peer The peer to send to the "onCanSend" or "onDidTimeout" function. true on success, false on failure.
int SocketCanReceiveEvent(uint64_t *eventID, uint64_t loopID, uint64_t socketID, void(*onCanReceive)(void *, void *), void *peer)
Sets a function pointer for the event where a socket is available for receiving data. This should be persistent.
loopID The loop id for socket onErrorReceived. socketID The socket id onCanReceive The function to call for the event. peer The peer to send to the "onCanReceive" or "onDidTimeout" function. true on success, false on failure.
int SocketAddEvent(uint64_t eventID, uint32_t timeout)
Adds an event to be pending.
eventID The event ID to add. timeout The time in milliseconds to issue a timeout for the event. 0 for no timeout. true if sucessful, false otherwise.
int SocketRemoveEvent(uint64_t eventID)
Removes an event so no more onErrorReceived are made.
eventID The event ID to remove true if sucessful, false otherwise.
void SocketFreeEvent(uint64_t eventID)
Makes an event non-pending and frees it.
eventID The event to free.
int32_t SocketSend(uint64_t socketID, uint8_t *data, uint32_t len)
Sends data to a socket. This should be non-blocking.
socketID The socket id to send to. data The data bytes to send. len The length of the data to send. The number of bytes actually sent, and _SOCKET_FAILURE on failure that suggests further data cannot be sent.
int32_t SocketReceive(uint64_t socketID, uint8_t *data, uint32_t len)
Receives data from a socket. This should be non-blocking.
socketID The socket id to receive data from. data The data bytes to write the data to. len The length of the data. The number of bytes actually written into "data", _SOCKET_CONNECTION_CLOSE on connection closure, 0 on no bytes received, and _SOCKET_FAILURE on failure.
int StartTimer(uint64_t loopID, uint64_t *timer, uint16_t time, void(*callback)(void *), void *arg)
Calls a callback every "time" seconds, until the timer is ended.
loopID The loop id for onErrorReceived. timer The timer sent by reference to be set. time The number of milliseconds between each call of the callback. callback The callback function. arg The callback argument.
void EndTimer(uint64_t timer)
Ends a timer.
timer The timer sent by reference to be set.
void CloseSocket(uint64_t socketID)
Closes a socket. The id should be freed, as well as any other data relating to this socket.
socketID The socket id to be closed.
void ExitEventLoop(uint64_t loopID)
Exits an event loop and frees all data relating to it.
loopID The loop ID. If zero, do nothing.
int NewSecureRandomGenerator(uint64_t *gen)
Returns an instance of a cryptographically secure random number generator.
The generator as a pointer or integer. true on success, false on failure.
void SecureRandomSeed(uint64_t gen)
Seeds the random number generator securely.
gen The generator.
void RandomSeed(uint64_t gen, uint64_t seed)
Seeds the generator from a 64-bit integer.
gen The generator. seed The 64-bit integer.
uint64_t SecureRandomInteger(uint64_t gen)
Generates a 64 bit integer.
gen The generator. The random 64-bit integer integer.
void FreeSecureRandomGenerator(uint64_t gen)
Frees the random number generator.
gen The generator.