GetBlocks.c
GetBlocks* newGetBlocks(uint32_t version, ChainDescriptor *chainDescriptor, ByteArray *stopAtHash, void(*onErrorReceived)(Error error, char *,...))
Creates a new GetBlocks object.
A new GetBlocks object.
References Object::destroy, ERROR_OUT_OF_MEMORY, freeGetBlocks, getObject, initGetBlocks.
GetBlocks* newGetBlocksFromData(ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new GetBlocks object from serialized data.
data Serialized GetBlocks data. A new GetBlocks object.
References Object::destroy, ERROR_OUT_OF_MEMORY, freeGetBlocks, getObject, initGetBlocksFromData.
GetBlocks* getGetBlocks(void *self)
Gets a GetBlocks from another object. Use this to avoid casts.
self The object to obtain the GetBlocks from. The GetBlocks object.
int initGetBlocks(GetBlocks *self, uint32_t version, ChainDescriptor *chainDescriptor, ByteArray *stopAtHash, void(*onErrorReceived)(Error error, char *,...))
Initialises a GetBlocks object.
self The GetBlocks object to initialise true on success, false on failure.
References FALSE, getMessage, incrementReferenceCount, initializeMessageFromObject, TRUE.
Referenced by newGetBlocks.
int initGetBlocksFromData(GetBlocks *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initialises a GetBlocks object from serialised data.
self The GetBlocks object to initialise data The serialised data. true on success, false on failure.
References FALSE, getMessage, initializeMessageFromByteArrayData, TRUE.
Referenced by newGetBlocksFromData.
void freeGetBlocks(void *vself)
Frees a GetBlocks object.
self The GetBlocks object to free.
References destroyMessage, destroyObject.
Referenced by newGetBlocks, newGetBlocksFromData.
uint32_t calculateGetBlocksLength(GetBlocks *self)
Calculates the length needed to serialise the object.
self The GetBlocks object. The length read on success, 0 on failure.
References getSizeOfVarLenInt.
uint16_t deserializeGetBlocks(GetBlocks *self)
Deserializes a GetBlocks so that it can be used as an object.
self The GetBlocks object The length read on success, 0 on failure.
References Message::bytes, deserializeChainDescriptor, destroyObject, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, getByteArraySubsectionReference, getMessage, ByteArray::length, newChainDescriptorFromData, Message::onErrorReceived, readInt32AsLittleEndianFromByteArray.
uint16_t serializeGetBlocks(GetBlocks *self)
Serializes a GetBlocks to the byte data.
self The GetBlocks object The length written on success, 0 on failure.
References Message::bytes, changeByteArrayDataReference, copyByteArrayToByteArray, destroyObject, ERROR_INIT_FAIL, ERROR_MESSAGE_SERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_NULL_BYTES, getByteArraySubsectionReference, getMessage, getSizeOfVarLenInt, ByteArray::length, Message::onErrorReceived, serializeChainDescriptor, setByteInByteArray.