Inventory.c
Inventory* createNewInventory(void(*onErrorReceived)(Error error, char *,...))
Creates a new Inventory object.
A new Inventory object.
References Object::destroy, destroyInventory, destroyObject, ERROR_OUT_OF_MEMORY, getObject, initializeInventory.
Inventory* createNewInventoryFromData(ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new Inventory object from serialised data.
data serialised Inventory data. A new Inventory object.
References Object::destroy, destroyInventory, destroyObject, ERROR_OUT_OF_MEMORY, getObject, initializeInventoryFromData.
Inventory* getInventory(void *self)
Gets a Inventory from another object. Use this to avoid casts.
self The object to obtain the Inventory from. The Inventory object.
int initializeInventory(Inventory *self, void(*onErrorReceived)(Error error, char *,...))
Initialises an Inventory object.
self The Inventory object to initialise one on success, zero on failure.
References FALSE, getMessage, initializeMessageFromObject, TRUE.
Referenced by createNewInventory.
int initializeInventoryFromData(Inventory *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initialises an Inventory object from serialised data.
self The Inventory object to initialise data The serialised data. one on success, zero on failure.
References FALSE, getMessage, initializeMessageFromByteArrayData, TRUE.
Referenced by createNewInventoryFromData.
void destroyInventory(void *selfIn)
destroys an Inventory object.
self The Inventory object to destroy.
References decrementReferenceCount, destroyMessage, destroyObject.
Referenced by createNewInventory, createNewInventoryFromData.
uint32_t calculateInventoryLength(Inventory *self)
Calculates the length needed to serialise the object.
self The Inventory object. The length read on success, 0 on failure.
References getSizeOfVarLenInt, INVENTORYVECTOR_TOTAL_SIZE.
uint32_t deserializeInventory(Inventory *self)
References Message::bytes, createNewInventoryVectorFromData, decodeVarLenInt, decrementReferenceCount, deserializeInventoryVector, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, ERROR_OUT_OF_MEMORY, getByteArraySubsectionReference, getMessage, ByteArray::length, Message::onErrorReceived, VarLenInt::storageSize, VarLenInt::value.
uint32_t serialiseInventory(Inventory *self)
Serialises a Inventory to the byte data.
self The Inventory object The length written on success, 0 on failure.
References Message::bytes, createVarLenIntFromUInt64, decrementReferenceCount, encodeVarLenInt, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_NULL_BYTES, getByteArraySubsectionReference, getMessage, ByteArray::length, Message::onErrorReceived, serializeInventoryVector, VarLenInt::storageSize, VarLenInt::value.