InventoryVector.h
InventoryVector* createNewInventoryVector(InventoryVectorType type, ByteArray *hash, void(*onErrorReceived)(Error error, char *,...))
Creates a new InventoryVector object.
A new InventoryVector object.
References Object::destroy, destroyInventoryVector, ERROR_OUT_OF_MEMORY, getObject, initializeInventoryVector.
InventoryVector* createNewInventoryVectorFromData(ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new InventoryVector object from serialised data.
data Serialised InventoryVector data. A new InventoryVector object.
References Object::destroy, destroyInventoryVector, ERROR_OUT_OF_MEMORY, getObject, initializeInventoryVectorFromData.
Referenced by deserializeInventory.
InventoryVector* getInventoryVector(void *self)
Gets a InventoryVector from another object. Use this to avoid casts.
self The object to obtain the InventoryVector from. The InventoryVector object.
int initializeInventoryVector(InventoryVector *self, InventoryVectorType type, ByteArray *hash, void(*onErrorReceived)(Error error, char *,...))
Initialises a InventoryVector object.
self The InventoryVector object to initialise true on success, false on failure.
References FALSE, getMessage, incrementReferenceCount, initializeMessageFromObject, TRUE.
Referenced by createNewInventoryVector.
int initializeInventoryVectorFromData(InventoryVector *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initialises a InventoryVector object from serialised data.
self The InventoryVector object to initialise data The serialised data. true on success, false on failure.
References FALSE, getMessage, initializeMessageFromByteArrayData, TRUE.
Referenced by createNewInventoryVectorFromData.
void destroyInventoryVector(void *self)
Frees a InventoryVector object.
self The InventoryVector object to free.
References decrementReferenceCount, destroyMessage.
Referenced by createNewInventoryVector, createNewInventoryVectorFromData.
uint32_t deserializeInventoryVector(InventoryVector *self)
Deserialises a InventoryVector so that it can be used as an object.
self The InventoryVector object The length read on success, 0 on failure.
References Message::bytes, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, getByteArraySubsectionReference, getMessage, INVENTORYVECTOR_HASH_FIELD_SIZE, INVENTORYVECTOR_TOTAL_SIZE, INVENTORYVECTOR_TYPE_FIELD_SIZE, ByteArray::length, Message::onErrorReceived, readInt32AsLittleEndianFromByteArray.
Referenced by deserializeInventory.
uint32_t serializeInventoryVector(InventoryVector *self)
Serialises a InventoryVector to the byte data.
self The InventoryVector object The length written on success, 0 on failure.
References Message::bytes, changeByteArrayDataReference, copyByteArrayToByteArray, ERROR_MESSAGE_SERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_NULL_BYTES, getMessage, INVENTORYVECTOR_TOTAL_SIZE, INVENTORYVECTOR_TYPE_FIELD_SIZE, ByteArray::length, Message::onErrorReceived, writeInt32AsLittleEndianIntoByteArray.
Referenced by serialiseInventory.