VarLenInt.c
VarLenInt decodeVarLenInt(ByteArray *bytes, uint32_t offset)
Decodes variable size integer from bytes into a VarLenInt structure.
bytes The byte array to decode a variable size integer from. offset Offset to start decoding from. The VarLenInt information
References getByteFromByteArray, readInt16AsLittleEndianFromByteArray, readInt32AsLittleEndianFromByteArray, readInt64AsLittleEndianFromByteArray, VarLenInt::storageSize, VarLenInt::value.
Referenced by deserializeTransaction, deserializeTransactionInput, deserializeTransactionOutput, deserializeWithOnlyHeaders, deserializeWithTransactions.
void encodeVarLenInt(ByteArray *bytes, uint32_t offset, VarLenInt varInt)
Encodes variable size integer into bytes.
bytes The byte array to encode a variable size integer into. offset Offset to start decoding from. varInt Variable integer structure to encode.
References setByteInByteArray, VarLenInt::storageSize, VarLenInt::value, writeInt16AsLittleEndianIntoByteArray, writeInt32AsLittleEndianIntoByteArray, writeInt64AsLittleEndianIntoByteArray.
Referenced by getTransactionInputHashForVerification, serializeBlock, serializeTransaction, serializeTransactionInput, serializeTransactionOutput.
VarLenInt createVarLenIntFromUInt64(uint64_t integer)
Returns a variable integer from an unsigned 64 bit integer.
integer The 64 bit integer A VarLenInt.
References getSizeOfVarLenInt, VarLenInt::storageSize, VarLenInt::value.
Referenced by getTransactionInputHashForVerification, serializeBlock, serializeTransaction, serializeTransactionInput, serializeTransactionOutput.
uint8_t getSizeOfVarLenInt(uint64_t value)
Returns the variable integer byte size of a 64 bit integer.
value The 64 bit integer The size of a variable length integer for this integer.
Referenced by calculateBlockLength, calculateTransactionLength, createVarLenIntFromUInt64, getTransactionInputHashForVerification.