Block.h
Block* createNewBlock(void(*onErrorReceived)(Error error, char *,...))
Creates a new Block object. Set the members after creating the block object.
A new Block object. Create a new Block by default
References deleteBlock, Object::destroy, getObject, initBlock, _ERROR_OUT_OF_MEMORY.
Block* createNewBlockFromByteArray(ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new Block object from serialized block data.
data Serialised block data. A new Block object. Create a new Block from a given ByteArray data
References deleteBlock, Object::destroy, getObject, initBlockFromByteArray, _ERROR_OUT_OF_MEMORY.
Block* createNewBlockWithOriginalBlock(void(*onErrorReceived)(Error error, char *,...))
Creates a new Block object with the original block for the bitcoin block chain. This will have serialised data as well as object data.
data Serialised block data. A new Block object.
Block* getBlock(void *self)
Gets a Block from another object. Use this to avoid casts.
self The object to obtain the Block from. The Block object. Get the Block
int initBlock(Block *self, void(*onErrorReceived)(Error error, char *,...))
Initializes a Block object.
self The Block object to initialize true on success, false on failure. Initializer by default
References FALSE, getMessage, TRUE.
Referenced by createNewBlock.
int initBlockFromByteArray(Block *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initializes a Block object from serialized data.
self The Block object to initialize data The serialized data. true on success, false on failure. Initialize the Block from ByteArray
References FALSE, getMessage, TRUE.
Referenced by createNewBlockFromByteArray.
int initBlockWithOriginalBlock(Block *self, void(*onErrorReceived)(Error error, char *,...))
Initializes a Block object with the original block for the bitcoin block chain. This will have serialized data as well as object data.
self The Block object to initialize. data Serialized block data. A new Block object.
References createNewByteArrayUsingDataCopy, decrementReferenceCount, deserializeBlock, FALSE, getMessage, TRUE.
Referenced by createNewBlockFromOriginalBlock.
void deleteBlock(void *vself)
Frees a Block object.
self The Block object to free. Destroy the Block
References decrementReferenceCount, destroyMessage, getObject.
Referenced by createNewBlock, createNewBlockFromByteArray, createNewBlockFromOriginalBlock.
void calculateBlockHash(Block *self, uint8_t *hash)
Calculates the hash for a block.
self The Block object. This should be serialized. The hash for the block to be set. This should be 32 bytes long. Calculate the hash for a Block.
References getDataFromByteArray, getMessage, Sha256.
Referenced by getBlockHash.
uint32_t calculateBlockLength(Block *self, int transactions)
Calculates the length needed to serialize the object.
self The Block object. transactions If true, the full block, if not true just the header. The length read on success, 0 on failure. Calculate the length of Block that is needed to serialize the object.
References calculateTransactionLength, getSizeOfVarLenInt.
uint32_t deserializeBlock(Block *self, int transactions)
Deserializes a Block so that it can be used as an object.
self The Block object transactions If true deserialize transactions. If false there do not deserialize for transactions. The length read on success, 0 on failure. Deserialize the Block
References Message::bytes, deserializeWithOnlyHeaders, deserializeWithTransactions, getByteFromByteArray, getByteArraySubsectionReference, getMessage, ByteArray::length, _ERROR_INIT_FAIL, _ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, _ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, Message::onErrorReceived, readInt32AsLittleEndianFromByteArray.
Referenced by initBlockWithOriginalBlock.
uint32_t deserializeWithOnlyHeaders(Block *self, uint8_t firstByte, ByteArray *bytes)
@ breif deserialize Block only with headers @ param self The Block object @ param firstByte uint8_t @ param bytes ByteArray object @ The length read on success, o on failure.
References decodeVarLenInt, getByteFromByteArray, getMessage, ByteArray::length, _ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, Message::onErrorReceived, VarLenInt::value.
Referenced by deserializeBlock.
uint32_t deserializeWithTransactions(Block *self, ByteArray *bytes)
@ breif deserialize Block with transactions @ param self The Block object @ param bytes ByteArray object @ The length read on success, o on failure.
References createNewTransactionFromByteArray, decodeVarLenInt, decrementReferenceCount, deserializeTransaction, getByteArraySubsectionReference, getMessage, ByteArray::length, _ERROR_INIT_FAIL, _ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, _ERROR_OUT_OF_MEMORY, Message::onErrorReceived, VarLenInt::storageSize, VarLenInt::value.
Referenced by deserializeBlock.
uint8_t* getBlockHash(Block *self)
Retrieves or calculates the hash for a block. Hashes taken from this function are cached.
self The Block object. This should be serialised. The hash for the block. This is a 32 byte long, double SHA-256 hash and is a pointer to the hash field in the block. Get the hash of the Block
References calculateBlockHash.
uint32_t serializeBlock(Block *self, int transactions)
Serializes a Block to the byte data.
self The Block object transactions If true serialize transactions. If false there do not serialize for transactions. The length read on success, 0 on failure.
References Message::bytes, createVarLenIntFromUInt64, dealWithSerializationHeader, dealWithSerializationTran, encodeVarLenInt, getMessage, ByteArray::length, _ERROR_MESSAGE_SERIALISATION_BAD_BYTES, _ERROR_MESSAGE_SERIALISATION_NULL_BYTES, Message::onErrorReceived, VarLenInt::storageSize.
void dealWithSerializationHeader(Block *self, ByteArray *bytes)
To deal with the header issue for serializeBlock. self The Block object bytes The ByteArray Serialize the header in a Block
References copyByteArrayToByteArray, writeInt32AsLittleEndianIntoByteArray.
Referenced by serializeBlock.
uint32_t dealWithSerializationTran(Block *self, ByteArray *bytes, uint32_t cursor, int transactions)
To dealt with the transaction issue for serializeBlock. self The Block object bytes The ByteArray cursor The initial cursor The cursor serialize the transactions in a Block
References Message::bytes, getByteArraySubsectionReference, getMessage, ByteArray::length, _ERROR_INIT_FAIL, _ERROR_MESSAGE_SERIALISATION_BAD_BYTES, Message::onErrorReceived, serializeTransaction, setByteInByteArray.
Referenced by serializeBlock.