Object.h
typedef struct Object Object
Object* createNewObject(void)
Creates a new Object.
Object
References destroyObject.
Object* getObject(void *self)
Casts the pointer to the Object; use this to avoid explicitly casting.
self Object
Referenced by createMessageFromByteArray, createNewBlock, createNewBlockFromByteArray, createNewBlockFromOriginalBlock, createNewByteArrayOfSize, createNewByteArrayUsingDataCopy, createNewMessage, createNewTransaction, createNewTransactionInput, createNewTransactionInputFromData, createNewTransactionOutput, createNewTransactionOutputFromData, deleteBlock, destroyByteArray, destroyTransaction, getByteArraySubsectionReference, initializeByteArraySubsectionReference, initByteArrayOfSize, initNewByteArrayFromData.
void destroyObject(void *self)
destructor
self void
Referenced by createNewObject, destroyByteArray, destroyMessage, serializeTransaction.
void decrementReferenceCount(void *self)
Decrease the number in the reference counter. (It keeps track of how many objects have been created). When the number goes to 0 - the object will be destroyed (assigned to NULL)
self void
References Object::referenceCount.
Referenced by deleteBlock, deserializeTransaction, deserializeTransactionInput, deserializeWithTransactions, destroyMessage, destroyTransaction, destroyTransactionInput, destroyTransactionOutput, initBlockWithOriginalBlock, serializeTransaction.
void incrementReferenceCount(void *self)
Increase the number in the reference counter. (It keeps track of how many objects have been created).
self void
References Object::referenceCount.
Referenced by addTransactionInput, addTransactionOutput, createMessageFromByteArray, initializeTransactionInput, initializeTransactionOutput.