Block.c
Block* createNewBlock(void(*onErrorReceived)(Error error, char *,...))
Creates a new Block object. Set the members after creating the block object.
Create a new Block by default
References deleteBlock, Object::destroy, getObject, initBlock, _ERROR_OUT_OF_MEMORY.
Block* createNewBlockFromByteArray(ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new Block object from serialized block data.
Create a new Block from a given ByteArray data
References deleteBlock, Object::destroy, getObject, initBlockFromByteArray, _ERROR_OUT_OF_MEMORY.
Block* createNewBlockFromOriginalBlock(void(*onErrorReceived)(Error error, char *,...))
Create a new Block from a default Block
References deleteBlock, Object::destroy, getObject, initBlockWithOriginalBlock, _ERROR_OUT_OF_MEMORY.
Block* getBlock(void *self)
Gets a Block from another object. Use this to avoid casts.
Get the Block
int initBlock(Block *self, void(*onErrorReceived)(Error error, char *,...))
Initializes a Block object.
Initializer by default
References FALSE, getMessage, TRUE.
Referenced by createNewBlock.
int initBlockFromByteArray(Block *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initializes a Block object from serialized data.
Initialize the Block from ByteArray
References FALSE, getMessage, TRUE.
Referenced by createNewBlockFromByteArray.
int initBlockWithOriginalBlock(Block *self, void(*onErrorReceived)(Error error, char *,...))
Initializes a Block object with the original block for the bitcoin block chain. This will have serialized data as well as object data.
self The Block object to initialize. data Serialized block data. A new Block object.
References createNewByteArrayUsingDataCopy, decrementReferenceCount, deserializeBlock, FALSE, getMessage, TRUE.
Referenced by createNewBlockFromOriginalBlock.
void deleteBlock(void *selfCopy)
Frees a Block object.
Destroy the Block
References decrementReferenceCount, destroyMessage, getObject.
Referenced by createNewBlock, createNewBlockFromByteArray, createNewBlockFromOriginalBlock.
void calculateBlockHash(Block *self, uint8_t *hash)
Calculates the hash for a block.
Calculate the hash for a Block.
References getDataFromByteArray, getMessage, Sha256.
Referenced by getBlockHash.
uint32_t calculateBlockLength(Block *self, int transactions)
Calculates the length needed to serialize the object.
Calculate the length of Block that is needed to serialize the object.
References calculateTransactionLength, getSizeOfVarLenInt.
uint32_t deserializeBlock(Block *self, int transactions)
Deserializes a Block so that it can be used as an object.
Deserialize the Block
References Message::bytes, deserializeWithOnlyHeaders, deserializeWithTransactions, getByteFromByteArray, getByteArraySubsectionReference, getMessage, ByteArray::length, _ERROR_INIT_FAIL, _ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, _ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, Message::onErrorReceived, readInt32AsLittleEndianFromByteArray.
Referenced by initBlockWithOriginalBlock.
uint32_t deserializeWithTransactions(Block *self, ByteArray *bytes)
@ breif deserialize Block with transactions @ param self The Block object @ param bytes ByteArray object @ The length read on success, o on failure.
References createNewTransactionFromByteArray, decodeVarLenInt, decrementReferenceCount, deserializeTransaction, getByteArraySubsectionReference, getMessage, ByteArray::length, _ERROR_INIT_FAIL, _ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, _ERROR_OUT_OF_MEMORY, Message::onErrorReceived, VarLenInt::storageSize, VarLenInt::value.
Referenced by deserializeBlock.
uint32_t deserializeWithOnlyHeaders(Block *self, uint8_t firstByte, ByteArray *bytes)
@ breif deserialize Block only with headers @ param self The Block object @ param firstByte uint8_t @ param bytes ByteArray object @ The length read on success, o on failure.
References decodeVarLenInt, getByteFromByteArray, getMessage, ByteArray::length, _ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, Message::onErrorReceived, VarLenInt::value.
Referenced by deserializeBlock.
uint8_t* getBlockHash(Block *self)
Retrieves or calculates the hash for a block. Hashes taken from this function are cached.
Get the hash of the Block
References calculateBlockHash.
uint32_t serializeBlock(Block *self, int transactions)
Serializes a Block to the byte data.
self The Block object transactions If true serialize transactions. If false there do not serialize for transactions. The length read on success, 0 on failure.
References Message::bytes, createVarLenIntFromUInt64, dealWithSerializationHeader, dealWithSerializationTran, encodeVarLenInt, getMessage, ByteArray::length, _ERROR_MESSAGE_SERIALISATION_BAD_BYTES, _ERROR_MESSAGE_SERIALISATION_NULL_BYTES, Message::onErrorReceived, VarLenInt::storageSize.
void dealWithSerializationHeader(Block *self, ByteArray *bytes)
Serialize the header in a Block
References copyByteArrayToByteArray, writeInt32AsLittleEndianIntoByteArray.
Referenced by serializeBlock.
uint32_t dealWithSerializationTran(Block *self, ByteArray *bytes, uint32_t cursor, int transactions)
serialize the transactions in a Block
References Message::bytes, getByteArraySubsectionReference, getMessage, ByteArray::length, _ERROR_INIT_FAIL, _ERROR_MESSAGE_SERIALISATION_BAD_BYTES, Message::onErrorReceived, serializeTransaction, setByteInByteArray.
Referenced by serializeBlock.