TransactionInput.c
TransactionInput* createNewTransactionInput(Script *script, uint32_t sequence, ByteArray *prevOutputHash, uint32_t prevOutputIndex, void(*onErrorReceived)(Error error, char *,...))
Creates a new TransactionInput object.
A new TransactionInput object.
References Object::destroy, destroyTransactionInput, getObject, initializeTransactionInput, _ERROR_OUT_OF_MEMORY.
TransactionInput* createNewTransactionInputFromData(ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new TransactionInput object from byte data.
data The byte data. A new TransactionInput object.
References Object::destroy, destroyTransactionInput, getObject, initializeTransactionInputFromData, _ERROR_OUT_OF_MEMORY.
Referenced by deserializeTransaction.
int initializeTransactionInput(TransactionInput *self, Script *script, uint32_t sequence, ByteArray *prevOutputHash, uint32_t prevOutputIndex, void(*onErrorReceived)(Error error, char *,...))
Initialises a TransactionInput object.
self The TransactionInput object to initialise true on success, false on failure.
References FALSE, getMessage, incrementReferenceCount, TRUE.
Referenced by createNewTransactionInput.
int initializeTransactionInputFromData(TransactionInput *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initialises a new TransactionInput object from the byte data.
self The TransactionInput object to initialise data The byte data. true on success, false on failure.
References FALSE, getMessage, TRUE.
Referenced by createNewTransactionInputFromData.
TransactionInput* getTransactionInput(void *self)
Gets a TransactionInput from another object. Use this to avoid casts.
self The object to obtain the TransactionInput from. The TransactionInput object.
void destroyTransactionInput(void *txIn)
Frees a TransactionInput object.
self The TransactionInput object to free.
References decrementReferenceCount, destroyMessage.
Referenced by createNewTransactionInput, createNewTransactionInputFromData.
uint32_t serializeTransactionInput(TransactionInput *self)
Serialises a TransactionInput to byte data.
self The TransactionInput object The length written on success, 0 on failure.
References Message::bytes, changeByteArrayDataReference, copyByteArrayToByteArray, createVarLenIntFromUInt64, encodeVarLenInt, getByteArray, getMessage, ByteArray::length, _ERROR_MESSAGE_SERIALISATION_BAD_BYTES, _ERROR_MESSAGE_SERIALISATION_BAD_DATA, _ERROR_MESSAGE_SERIALISATION_NULL_BYTES, Message::onErrorReceived, VarLenInt::storageSize, writeInt32AsLittleEndianIntoByteArray.
Referenced by serializeTransaction.
uint32_t deserializeTransactionInput(TransactionInput *self)
Deserialises a TransactionInput so that it can be used as an object.
self The TransactionInput object The length read on success, 0 on failure.
References Message::bytes, createNewScriptFromReference, decodeVarLenInt, decrementReferenceCount, getByteArraySubsectionReference, getMessage, ByteArray::length, _ERROR_INIT_FAIL, _ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, _ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, Message::onErrorReceived, readInt32AsLittleEndianFromByteArray, VarLenInt::storageSize, VarLenInt::value.
Referenced by deserializeTransaction.