Transaction.c
Transaction* createNewTransaction(uint32_t lockTime, uint32_t version, void(*onErrorReceived)(Error error, char *,...))
Creates a new Transaction object with no inputs or outputs.
A new Transaction object.
References Object::destroy, destroyTransaction, getObject, initializeTransaction, _ERROR_OUT_OF_MEMORY.
Transaction* createNewTransactionFromByteArray(ByteArray *bytes, void(*onErrorReceived)(Error error, char *,...))
Creates a new Transaction object from byte data. Should be serialised for object data.
A new Transaction object.
References initializeTransactionFromByteArray, _ERROR_OUT_OF_MEMORY.
Referenced by deserializeWithTransactions.
int initializeTransaction(Transaction *self, uint32_t lockTime, uint32_t version, void(*onErrorReceived)(Error error, char *,...))
Initialises a Transaction object.
self The Transaction object to initialise true on success, false on failure.
References FALSE, getMessage, TRUE.
Referenced by createNewTransaction.
int initializeTransactionFromByteArray(Transaction *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new Transaction object from byte data. Should be serialised for object data.
A new Transaction object.
References FALSE, getMessage, TRUE.
Referenced by createNewTransactionFromByteArray.
void destroyTransaction(void *transaction)
Destructor; destroys a Transaction object.
self The Transaction object to free.
References decrementReferenceCount, destroyMessage, getObject.
Referenced by createNewTransaction.
Transaction* getTransaction(void *self)
Gets a Transaction from another object. Use this to avoid casts.
self The object to obtain the Transaction from. The Transaction object.
int addTransactionInput(Transaction *self, TransactionInput *input)
Adds an TransactionInput to the Transaction.
self The Transaction object. input The TransactionInput object. true if the transaction input was added successfully and false on error.
References addTransactionInputWithoutReference, incrementReferenceCount.
int addTransactionOutput(Transaction *self, TransactionOutput *output)
Adds an TransactionInput to the Transaction.
self The Transaction object. input The TransactionOutput object. true if the transaction output was added successfully and false on error.
References addTransactionInputWithoutReference, incrementReferenceCount.
int addTransactionInputWithoutReference(Transaction *self, TransactionInput *input)
Adds an TransactionInput to the Transaction without retaining it.
self The Transaction object. input The TransactionInput object. true if the transaction input was taken successfully and false on error.
References FALSE, TRUE.
Referenced by addTransactionInput, addTransactionOutput.
int addTransactionOutputWithoutReference(Transaction *self, TransactionOutput *output)
Adds an TransactionOutput to the Transaction without retaining it.
self The Transaction object. input The TransactionOutput object. true if the transaction output was taken successfully and false on error.
References FALSE, TRUE.
void calculateTransactionHash(Transaction *self, uint8_t *hash)
Calculates the hash for a transaction.
self The Transaction object. This should be serialised. The hash for the transaction to be set. This should be 32 bytes long.
References getDataFromByteArray, getMessage, ByteArray::length, Sha256.
Referenced by getTransactionHash.
uint8_t* getTransactionHash(Transaction *self)
Retrieves or calculates the hash for a transaction. Hashes taken from this function are cached.
self The Transaction object. This should be serialised. The hash for the transaction. This is a 32 byte long, double SHA-256 hash and is a pointer to the hash field in the transaction.
References calculateTransactionHash.
uint32_t calculateTransactionLength(Transaction *self)
Calculates the length of an Transaction; this is needed to serialise the object.
self The Transaction object. The length of the Transaction on success, 0 on failure.
References getSizeOfVarLenInt.
Referenced by calculateBlockLength.
int isCoinBase(Transaction *self)
Determines if a transaction is a coinbase transaction or not.
self The Transaction object. true if the transaction is a coin-base transaction or false if not.
References isNullByteArray.
uint32_t serializeTransaction(Transaction *self)
Serialises a Transaction to byte data.
self The Transaction object. The length read on success, 0 on failure.
References Message::bytes, createVarLenIntFromUInt64, decrementReferenceCount, destroyObject, encodeVarLenInt, getByteArraySubsectionReference, getMessage, ByteArray::length, _ERROR_INIT_FAIL, _ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, _ERROR_MESSAGE_SERIALISATION_BAD_BYTES, _ERROR_MESSAGE_SERIALISATION_NULL_BYTES, Message::onErrorReceived, serializeTransactionInput, serializeTransactionOutput, VarLenInt::storageSize, writeInt32AsLittleEndianIntoByteArray.
Referenced by dealWithSerializationTran.
uint32_t deserializeTransaction(Transaction *self)
Deserialises a Transaction so that it can be used as an object.
self The Transaction object The length read on success, 0 on failure.
References Message::bytes, createNewTransactionInputFromData, createNewTransactionOutputFromData, decodeVarLenInt, decrementReferenceCount, deserializeTransactionInput, deserializeTransactionOutput, getByteArraySubsectionReference, getMessage, ByteArray::length, _ERROR_INIT_FAIL, _ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, _ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, _ERROR_OUT_OF_MEMORY, Message::onErrorReceived, readInt32AsLittleEndianFromByteArray, VarLenInt::storageSize, VarLenInt::value.
Referenced by deserializeWithTransactions.
TransactionHashStatus getTransactionInputHashForVerification(void *txIn, ByteArray *prevOutSubScript, uint32_t input, SignatureType signType, uint8_t *hash)
Gets the hash for signing or signature checking for a transaction input. The transaction input needs to contain the outPointerHash, outPointerIndex and sequence. If these are modifed afterwards then the signiture is invalid.
TRANSACTION SIGNING vself The Transaction object. prevOutSubScript The sub script from the output. Must be the correct one or the signiture will be invalid. input The index of the input to sign. signType The type of signature to get the data for. hash The 32 byte data hash for signing or checking signatures. _TX_HASH_OK if the hash has been retreived with no problems. _TX_HASH_BAD is returned if the hash is invalid and _TX_HASH_ERR is returned upon an error.
References copyByteArrayToByteArray, createVarLenIntFromUInt64, createNewByteArrayOfSize, encodeVarLenInt, getDataFromByteArray, getByteArray, getMessage, getSizeOfVarLenInt, ByteArray::length, _ERROR_TRANSACTION_FEW_INPUTS, _ERROR_TRANSACTION_FEW_OUTPUTS, _SIGHASH_ANYONECANPAY, _SIGHASH_NONE, _SIGHASH_SINGLE, Sha256, Message::onErrorReceived, VarLenInt::storageSize, TX_HASH_BAD, TX_HASH_FAIL, TX_HASH_GOOD, VarLenInt::value, writeInt32AsLittleEndianIntoByteArray, writeInt64AsLittleEndianIntoByteArray.