Message.h
typedef struct Message Message
Structure for Message objects.
Message.h
Message* createNewMessage(void(*onErrorReceived)(Error error, char *,...))
Creates a new Message object. This message will be created with object data and not with byte data. The message can be serialised for the byte data used over the network.
@returns A new Message object.
References Object::destroy, destroyMessage, FALSE, getObject, _ERROR_OUT_OF_MEMORY, Object::referenceCount.
Message* getMessage(void *self)
Gets a Message from another object. Use this to avoid casts.
self The object to obtain the Message from. The Message object.
Referenced by calculateBlockHash, calculateTransactionHash, dealWithSerializationTran, deserializeBlock, deserializeTransaction, deserializeTransactionInput, deserializeTransactionOutput, deserializeWithOnlyHeaders, deserializeWithTransactions, getTransactionInputHashForVerification, initializeTransaction, initializeTransactionFromByteArray, initializeTransactionInput, initializeTransactionInputFromData, initializeTransactionOutput, initializeTransactionOutputFromData, initBlock, initBlockFromByteArray, initBlockWithOriginalBlock, serializeBlock, serializeTransaction, serializeTransactionInput, serializeTransactionOutput.
Message* createMessageFromByteArray(Message *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initialises a Message object from byte data.
self The Message object to initialise data The byte data for the object. The data will not be copied but retained by this object. Message
References FALSE, getObject, incrementReferenceCount, Object::referenceCount.
void destroyMessage(void *self)
destroys the memory allocated to a Message object.
self The Message object to free.
References decrementReferenceCount, destroyObject.
Referenced by createNewMessage, deleteBlock, destroyTransaction, destroyTransactionInput, destroyTransactionOutput.