Message.h
typedef struct Message Message
Message* createNewMessage(void(*onErrorReceived)(Error error, char *,...))
Creates a new Message.
Creates a new Message object. This message will be created with object data and not with byte data. The message can be serialised for the byte data used over the network.MessageA new Message object.
References Object::destroy, destroyMessage, ERROR_OUT_OF_MEMORY, FALSE, getObject, Object::referenceCount.
Message* getMessage(void *self)
getter
Gets a Message from another object. Use this to avoid casts. self Message Object self The object to obtain the Message from. The Message object.
Referenced by calculateBlockHash, calculateTransactionHash, dealWithSerializationTran, deserializeBlock, deserializeBlockHeaders, deserializeChainDescriptor, deserializeGetBlocks, deserializeInventory, deserializeInventoryVector, deserializePingPongMessage, deserializeTransaction, deserializeTransactionInput, deserializeTransactionOutput, deserializeWithOnlyHeaders, deserializeWithTransactions, getTransactionInputHashForVerification, initBlock, initBlockFromByteArray, initBlockHeaders, initBlockHeadersFromData, initBlockWithGenesisBlockInfo, initChainDescriptor, initChainDescriptorFromData, initGetBlocks, initGetBlocksFromData, initializeInventory, initializeInventoryFromData, initializeInventoryVector, initializeInventoryVectorFromData, initializePingPongMessage, initializePingPongMessageFromData, initializeTransactionInput, initializeTransactionInputFromData, initializeTransactionOutput, initializeTransactionOutputFromData, serialiseInventory, serializeBlock, serializeBlockHeaders, serializeChainDescriptor, serializeGetBlocks, serializeInventoryVector, serializePingPongMessage, serializeTransaction, serializeTransactionInput, serializeTransactionOutput, setUpTransactionData, setUpTransactionDataUsingByteArray.
int* setByteArrayInMessage(Message *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
References FALSE, getObject, incrementReferenceCount, Object::referenceCount, TRUE.
int initializeMessageFromObject(Message *self, void(*onErrorReceived)(Error error, char *,...))
Initialises a Message object.
self The Message object to initialise TRUE on success, FALSE on failure.
References FALSE, getObject, setObjectRefCountToOne, TRUE.
Referenced by initBlock, initBlockHeaders, initChainDescriptor, initGetBlocks, initializeInventory, initializeInventoryVector, initializePingPongMessage, initializeTransactionInput, initializeTransactionOutput.
int initializeMessageFromByteArrayData(Message *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initialises a Message object from byteArray data.
self The Message object to initialise data The byte data for the object. The data will not be copied but referenced by this object. TRUE on success, FALSE on failure.
References FALSE, getObject, incrementReferenceCount, setObjectRefCountToOne, TRUE.
Referenced by initBlockFromByteArray, initBlockHeadersFromData, initBlockWithGenesisBlockInfo, initChainDescriptorFromData, initGetBlocksFromData, initializeInventoryFromData, initializeInventoryVectorFromData, initializePingPongMessageFromData, initializeTransactionInputFromData, initializeTransactionOutputFromData.
void destroyMessage(void *self)
destroy Message
destroys the memory allocated to a Message object. message self The Message object to free.
References decrementReferenceCount, destroyObject.
Referenced by createNewMessage, deleteBlock, destroyInventory, destroyInventoryVector, destroyPingPongMessage, destroyTransaction, destroyTransactionInput, destroyTransactionOutput, freeBlockHeaders, freeChainDescriptor, freeGetBlocks.