NetworkFunctions.h
const uint8_t IPv4Start[12][12]
const uint8_t SITTStart[12][12]
const uint8_t RFC6052Start[12][12]
IPType getIPType(uint8_t *IP)
Determines the type of IP, including validity.
IP The IP address to check. The IP type.
References IP_6TO4, IP_HENET, IP_I2P, IP_INVALID, IP_IPv4, IP_IPv6, IP_LOCAL, IP_RFC6052, IP_SITT, IP_TEREDO, IP_TOR, isI2P, isIPv4, isTor.
int isI2P(uint8_t *IP)
Determines if an IP address is an GarliCat I2P hidden service representation.
IP The IP address to check. true if the IP address is an I2P address, false otherwise.
Referenced by getIPType.
int isIPv4(uint8_t *IP)
Determines if an IP address is an IPv4 address.
IP The IP address to check. true if the IP address is IPv4, false otherwise.
Referenced by getIPType.
int isTor(uint8_t *IP)
Determines if an IP address is an OnionCat Tor hidden service representation.
IP The IP address to check. true if the IP address is a Tor address, false otherwise.
Referenced by getIPType.