NodeDiscovery.c
NodeDiscovery* newNodeDiscovery()
Creates a new NodeDiscovery object.
A new NodeDiscovery object.
References Object::destroy, destroyNodeDiscovery, getObject, initNodeDiscovery.
NodeDiscovery* getNodeDiscovery(void *self)
Gets a NodeDiscovery from an object. Use this to avoid casts.
self The object to obtain the NodeDiscovery from. The NodeDiscovery object.
int initNodeDiscovery(NodeDiscovery *self)
Initializes a NodeDiscovery object.
self The NodeDiscovery object to initialize TRUE on success, FALSE on failure.
References FALSE, getObject, Object::referenceCount, TRUE.
Referenced by newNodeDiscovery.
void destroyNodeDiscovery(void *self)
Destroys an NodeDiscovery object.
self The NodeDiscovery object to free.
References destroyObject.
Referenced by newNodeDiscovery.
char* extractIp(char *str1)
Referenced by getExtIP.
char* getExtIP(char *dest)
Connects to a specified host. IPv4 compatible only!!!
find flags here http://cboard.cprogramming.com/cplusplus-programming/128326-undefined-symbol-when-compiling-socket-program.html
References errno, extractIp.