Object.h
typedef struct Object Object
Object* createNewObject(void)
Creates a new Object.
Object
References destroyObject.
Object* getObject(void *self)
Casts the pointer to the Object; use this to avoid explicitly casting.
self Object
Referenced by createNewBlock, createNewBlockFromByteArray, createNewBlockFromOriginalBlock, createNewByteArrayFromData, createNewByteArrayOfSize, createNewByteArrayUsingDataCopy, createNewInventory, createNewInventoryFromData, createNewInventoryVector, createNewInventoryVectorFromData, createNewMessage, createNewPingPongMessage, createNewPingPongMessageFromData, createNewTransaction, createNewTransactionInput, createNewTransactionInputFromData, createNewTransactionOutput, createNewTransactionOutputFromData, deleteBlock, destroyByteArray, destroyTransaction, getByteArraySubsectionReference, initByteArrayOfSize, initializeByteArraySubsectionReference, initializeMessageFromByteArrayData, initializeMessageFromObject, initNewByteArrayFromData, initNewByteArrayUsingDataCopy, initNodeDiscovery, NewAddressFromRIPEMD160Hash, newBlockHeaders, newBlockHeadersFromData, newChainDescriptor, newChainDescriptorFromData, newGetBlocks, newGetBlocksFromData, newNodeDiscovery, NewVersionChecksumBytesFromString, setByteArrayInMessage, setUpTransactionData, setUpTransactionDataUsingByteArray.
void destroyObject(void *self)
destructor
self void
Referenced by createNewInventory, createNewInventoryFromData, createNewObject, deserializeBlockHeaders, deserializeGetBlocks, destroyByteArray, destroyInventory, destroyMessage, destroyNodeDiscovery, executeScript, freeBlockHeaders, freeChainDescriptor, freeGetBlocks, serializeBlockHeaders, serializeGetBlocks, serializeTransaction.
void decrementReferenceCount(void *self)
Decrease the number in the reference counter. (It keeps track of how many objects have been created). When the number goes to 0 - the object will be destroyed (assigned to NULL)
self void
References Object::referenceCount.
Referenced by deleteBlock, deserializeInventory, deserializeTransaction, deserializeTransactionInput, deserializeWithTransactions, destroyInventory, destroyInventoryVector, destroyMessage, destroyTransaction, destroyTransactionInput, destroyTransactionOutput, FreeVersionChecksumBytes, initBlockWithGenesisBlockInfo, serialiseInventory, serializeTransaction.
void incrementReferenceCount(void *self)
Increase the number in the reference counter. (It keeps track of how many objects have been created).
self void
References Object::referenceCount.
Referenced by addBlockHeaderToBlockHeaderList, addHashToChainDescriptor, addTransactionInput, addTransactionOutput, initGetBlocks, initializeInventoryVector, initializeMessageFromByteArrayData, initializeTransactionInput, initializeTransactionOutput, InitVersionChecksumBytesFromString, setByteArrayInMessage, setUpTransactionDataUsingByteArray.
int setObjectRefCountToOne(Object *self)
resets the reference counts to an object to one
self The Object to reset its referenceCount This should always returns TRUE.
References TRUE.
Referenced by initializeMessageFromByteArrayData, initializeMessageFromObject.