PingPongMessage.h
PingPongMessage* createNewPingPongMessage(uint64_t ID, void(*onErrorReceived)(Error error, char *,...))
Creates a new PingPongMessage object.
ID The identifier used in a ping/pong communication. Set to zero if you don't want to overlap ping messages A new PingPongMessage object.
References Object::destroy, destroyPingPongMessage, ERROR_OUT_OF_MEMORY, getObject, initializePingPongMessage.
PingPongMessage* createNewPingPongMessageFromData(ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new PingPongMessage object from serialised data.
data Serialised PingPongMessage data. A new PingPongMessage object.
References Object::destroy, destroyPingPongMessage, ERROR_OUT_OF_MEMORY, getObject, initializePingPongMessageFromData.
PingPongMessage* getPingPongMessage(void *self)
Gets a PingPongMessage from another object. Use this to avoid casts.
self The object to obtain the PingPongMessage from. The PingPongMessage object.
int initializePingPongMessage(PingPongMessage *self, uint64_t ID, void(*onErrorReceived)(Error error, char *,...))
Initialises a PingPongMessage object.
self The PingPongMessage object to initialise ID The identifier used in a ping/pong communcation. Set to zero if you don't want to overlap ping messages One on success, Zero on failure.
References FALSE, getMessage, initializeMessageFromObject, TRUE.
Referenced by createNewPingPongMessage.
int initializePingPongMessageFromData(PingPongMessage *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initialises a PingPongMessage object from serialised data.
self The PingPongMessage object to initialise data The serialised data. One on success, Zero on failure.
References FALSE, getMessage, initializeMessageFromByteArrayData, TRUE.
Referenced by createNewPingPongMessageFromData.
void destroyPingPongMessage(void *self)
Frees a PingPongMessage object.
self The PingPongMessage object to free.
References destroyMessage.
Referenced by createNewPingPongMessage, createNewPingPongMessageFromData.
uint8_t deserializePingPongMessage(PingPongMessage *self)
Deserialises a PingPongMessage so that it can be used as an object.
self The PingPongMessage object Length read if successful, zero otherwise.
References Message::bytes, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, getMessage, ByteArray::length, Message::onErrorReceived, readInt64AsLittleEndianFromByteArray.
uint8_t serializePingPongMessage(PingPongMessage *self)
Serialises a PingPongMessage to the byte data.
self The PingPongMessage object Length written if successful, zero otherwise.
References Message::bytes, ERROR_MESSAGE_SERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_NULL_BYTES, getMessage, ByteArray::length, Message::onErrorReceived, writeInt64AsLittleEndianIntoByteArray.