Script.h
typedef struct ScriptByteVector ScriptByteVector
Structure for a byte vector; Byte vectors are interpreted as little-endian variable-length integers with the most significant bit determining the sign of the integer.
typedef ByteArray Script
ScriptStack createEmptyScriptStack(void)
Returns a new empty scriptstack.
A script is a array of bytes The new empty stack.
References ScriptStack::elements, ScriptStack::length.
Referenced by executeScript.
Script* createNewScriptFromReference(Script *program, uint32_t offset, uint32_t len)
Creates a new Script object.
A new Script object. Constructor
References getByteArraySubsectionReference.
Referenced by deserializeTransactionInput, deserializeTransactionOutput.
ScriptExecutionStatus executeScript(Script *self, ScriptStack *stack, TransactionHashStatus(*getHashForSignature)(void *, ByteArray *, uint32_t, SignatureType, uint8_t *), void *transaction, uint32_t inputIndex, int p2sh)
Executes a bitcoin script.
self The Script object with the program stack A pointer to the input stack for the program. getHashForSig A pointer to the function to get the hash for checking the signature. Should take a Transaction object, input index and the SignatureType and the Dependencies object. transaction Transaction for checking the signatures. inputIndex The index of the input for the signature. p2sh If FALSE, do not allow any P2SH matches. GOOD_SCRIPT if the program ended with true, BAD_SCRIPT on script failure or SCRIPT_ERR if an error occurred with the interpreter such as running of of memory.
References BAD_SCRIPT, convertInt64ToScriptByteVector, convertScriptByteVectorToInt64, copyByteVectorFromScriptStack, createEmptyScriptStack, createNewByteArrayFromData, createNewScriptStackFromData, ScriptByteVector::data, destroyObject, ECDSAVerify, ScriptStack::elements, ERROR_OUT_OF_MEMORY, executeScript, FALSE, getByteArrayData, getByteFromByteArray, getTransactionInputHashForVerification, GOOD_SCRIPT, isP2SHScript, ScriptStack::length, ScriptByteVector::length, ByteArray::length, ByteArray::onErrorReceived, popElementFromStack, pushScriptByteVectorOntoScriptStack, readInt16AsLittleEndianFromByteArray, readInt32AsLittleEndianFromByteArray, removeElementFromStack, removeSignatureFromStackScript, Ripemd160, SCRIPT_ERR, SCRIPT_OPCODE_0NOTEQUAL, SCRIPT_OPCODE_1, SCRIPT_OPCODE_16, SCRIPT_OPCODE_1ADD, SCRIPT_OPCODE_1NEGATE, SCRIPT_OPCODE_1SUB, SCRIPT_OPCODE_2DIV, SCRIPT_OPCODE_2DROP, SCRIPT_OPCODE_2DUP, SCRIPT_OPCODE_2MUL, SCRIPT_OPCODE_2OVER, SCRIPT_OPCODE_2ROT, SCRIPT_OPCODE_2SWAP, SCRIPT_OPCODE_3DUP, SCRIPT_OPCODE_ABS, SCRIPT_OPCODE_ADD, SCRIPT_OPCODE_AND, SCRIPT_OPCODE_BOOLAND, SCRIPT_OPCODE_BOOLOR, SCRIPT_OPCODE_CAT, SCRIPT_OPCODE_CHECKMULTISIG, SCRIPT_OPCODE_CHECKMULTISIGVERIFY, SCRIPT_OPCODE_CHECKSIG, SCRIPT_OPCODE_CHECKSIGVERIFY, SCRIPT_OPCODE_CODESEPARATOR, SCRIPT_OPCODE_DEPTH, SCRIPT_OPCODE_DIV, SCRIPT_OPCODE_DROP, SCRIPT_OPCODE_DUP, SCRIPT_OPCODE_ELSE, SCRIPT_OPCODE_ENDIF, SCRIPT_OPCODE_EQUAL, SCRIPT_OPCODE_EQUALVERIFY, SCRIPT_OPCODE_FROMALTSTACK, SCRIPT_OPCODE_GREATERTHAN, SCRIPT_OPCODE_GREATERTHANOREQUAL, SCRIPT_OPCODE_HASH160, SCRIPT_OPCODE_HASH256, SCRIPT_OPCODE_IF, SCRIPT_OPCODE_IFDUP, SCRIPT_OPCODE_INVALID, SCRIPT_OPCODE_INVERT, SCRIPT_OPCODE_LEFT, SCRIPT_OPCODE_LESSTHAN, SCRIPT_OPCODE_LESSTHANOREQUAL, SCRIPT_OPCODE_LSHIFT, SCRIPT_OPCODE_MAX, SCRIPT_OPCODE_MIN, SCRIPT_OPCODE_MOD, SCRIPT_OPCODE_MUL, SCRIPT_OPCODE_NEGATE, SCRIPT_OPCODE_NIP, SCRIPT_OPCODE_NOP, SCRIPT_OPCODE_NOT, SCRIPT_OPCODE_NOTIF, SCRIPT_OPCODE_NUMEQUAL, SCRIPT_OPCODE_NUMEQUALVERIFY, SCRIPT_OPCODE_NUMNOTEQUAL, SCRIPT_OPCODE_OR, SCRIPT_OPCODE_OVER, SCRIPT_OPCODE_PICK, SCRIPT_OPCODE_PUSHDATA1, SCRIPT_OPCODE_PUSHDATA2, SCRIPT_OPCODE_RESERVED, SCRIPT_OPCODE_RETURN, SCRIPT_OPCODE_RIGHT, SCRIPT_OPCODE_RIPEMD160, SCRIPT_OPCODE_ROLL, SCRIPT_OPCODE_ROT, SCRIPT_OPCODE_RSHIFT, SCRIPT_OPCODE_SHA1, SCRIPT_OPCODE_SHA256, SCRIPT_OPCODE_SIZE, SCRIPT_OPCODE_SUB, SCRIPT_OPCODE_SUBSTR, SCRIPT_OPCODE_SWAP, SCRIPT_OPCODE_TOALTSTACK, SCRIPT_OPCODE_TUCK, SCRIPT_OPCODE_VERIF, SCRIPT_OPCODE_VERIFY, SCRIPT_OPCODE_VERNOTIF, SCRIPT_OPCODE_WITHIN, SCRIPT_OPCODE_XOR, Sha160, Sha256, topElementEvaluatesToTrue, TRUE, TX_HASH_FAIL, TX_HASH_GOOD.
Referenced by executeScript.
int isP2SHScript(Script *self)
Determines if a script object matches the P2SH template; i.e. BIP 0016 see https://en.bitcoin.it/wiki/BIP_0016.
self The Script object. one if the script matches the P2SH template, zero otherwise.
References getByteFromByteArray, SCRIPT_OPCODE_EQUAL, SCRIPT_OPCODE_HASH160.
Referenced by executeScript.
ScriptByteVector copyByteVectorFromScriptStack(ScriptStack *stack, uint8_t fromTop)
Returns a copy of a stack item, "fromTop" from the top.
stack A pointer to the stack. fromTop Number of items from the top to copy. A copy of the stack item which should be freed.
References ScriptByteVector::data, ScriptStack::elements, ScriptByteVector::length, ScriptStack::length.
Referenced by executeScript.
int pushScriptByteVectorOntoScriptStack(ScriptStack *stack, ScriptByteVector item)
Push a ScriptByteVector item onto the stack which is freed by the stack.
stack A pointer to the ScriptStack to push data onto. data The item to push on the stack.
References ScriptStack::elements, FALSE, ScriptStack::length, TRUE.
Referenced by executeScript.
int topElementEvaluatesToTrue(ScriptStack *stack)
Evaluates the top ScriptByteVector on a ScriptStack as a boolean. False if 0 or -0.
stack The ScriptStack. The boolean result.
References ScriptByteVector::data, ScriptStack::elements, FALSE, ScriptByteVector::length, ScriptStack::length, TRUE.
Referenced by executeScript.
void removeElementFromStack(ScriptStack *stack)
Removes top ScriptByteVector from the stack.
stack A pointer to the stack to remove the data.
References ScriptByteVector::data, ScriptStack::elements, ScriptStack::length.
Referenced by executeScript.
ScriptByteVector popElementFromStack(ScriptStack *stack)
Pops the top ScriptByteVector off the ScriptStack.
stack A pointer to the stack to remove the data. ScriptByteVector the top ScriptByteVector on the stack
References ScriptStack::elements, ScriptStack::length.
Referenced by executeScript.
ScriptByteVector convertInt64ToScriptByteVector(ScriptByteVector byteVector, int64_t int64)
Converts a int64_t into a ScriptByteVector.
byteVector Pass in a ScriptByteVector for reallocating data. int64 The 64 bit signed integer. A ScriptByteVector.
References ScriptByteVector::data, ScriptByteVector::length.
Referenced by executeScript.
int64_t convertScriptByteVectorToInt64(ScriptByteVector byteVector)
Converts a ScriptByteVector to a 64 bit signed integer.
item The ScriptByteVector to convert A 64 bit signed integer.
References ScriptByteVector::data, ScriptByteVector::length.
Referenced by executeScript.
void removeSignatureFromStackScript(uint8_t *subScript, uint32_t *subScriptLen, ScriptByteVector signature)
Removes occurrences of a signature from script data.
subScript The sub script to remove signatures from. subScriptLen A pointer to the length of the sub script. The length will be modified to the new length. signature The signature to be found and removed.
References ScriptByteVector::data, ScriptByteVector::length, SCRIPT_OPCODE_PUSHDATA1, SCRIPT_OPCODE_PUSHDATA2.
Referenced by executeScript.
Script* createNewScriptStackFromData(uint8_t *data, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
Creates a new Script using data.
data The data. This should be dynamically allocated. The new ByteArray object will take care of it's memory management so do not free this data once passed into this constructor. size Size in bytes for the new array. onErrorReceived Struct for handling errors. The new Script object.
References createNewByteArrayFromData.
Referenced by executeScript.
Script* createNewScriptStackUsingCopyOfData(uint8_t *data, uint32_t size, void(*onErrorReceived)(Error error, char *,...))
Creates a new Script using a copy of data.
data The data is copied size Size in bytes for the new array. onErrorReceived Struct for handling errors. The new Script object.
References createNewByteArrayUsingDataCopy.