Transaction.h
Transaction* createNewTransaction(uint32_t lockTime, uint32_t version, void(*onErrorReceived)(Error error, char *,...))
Creates a new Transaction object with no inputs or outputs.
lockTime The timestamp which determines if this transaction is locked. 0 means the transaction is always locked; values < 500000000 indicate the block number at which this transaction is locked while values >= 500000000 indicate the UNIX timestamp at which this transaction is locked version Transaction data format version onErrorReceived Error handler A new Transaction object.
References Object::destroy, destroyTransaction, ERROR_OUT_OF_MEMORY, getObject, setUpTransactionData.
Transaction* createNewTransactionFromByteArray(ByteArray *bytes, void(*onErrorReceived)(Error error, char *,...))
Creates a new Transaction object from byte data. Should be serialised for object data.
bytes Array of bytes to be used for creation of transaction onErrorReceived Error handler A new Transaction object.
References ERROR_OUT_OF_MEMORY, setUpTransactionDataUsingByteArray.
Referenced by deserializeWithTransactions.
int setUpTransactionData(Transaction *self, uint32_t lockTime, uint32_t version, void(*onErrorReceived)(Error error, char *,...))
Sets up the fields of a Transaction object.
self The Transaction object whose fields are to be set lockTime The timestamp which determines if this transaction is locked. 0 means the transaction is always locked; values < 500000000 indicate the block number at which this transaction is locked while values >= 500000000 indicate the UNIX timestamp at which this transaction is locked version Transaction data format version onErrorReceived Error handler 1 on success, 0 on failure.
References Message::bytes, Message::expectResponse, FALSE, getMessage, getObject, Message::onErrorReceived, Object::referenceCount, TRUE.
Referenced by createNewTransaction.
int setUpTransactionDataUsingByteArray(Transaction *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Sets up the fields of a Transaction object using a byteArray object that was passed in.
bytes Array of bytes to be used for creation of transaction onErrorReceived Error handler 1 on success, 0 on failure.
References Message::bytes, Message::expectResponse, FALSE, getMessage, getObject, incrementReferenceCount, Message::onErrorReceived, Object::referenceCount, TRUE.
Referenced by createNewTransactionFromByteArray.
void destroyTransaction(void *self)
Destructor; destroys a Transaction object.
self The Transaction object to free. void
References decrementReferenceCount, destroyMessage, getObject.
Referenced by createNewTransaction.
Transaction* getTransaction(void *self)
Gets a Transaction from another object. Use this to avoid explicit casts.
self The object to obtain the Transaction from. A Transaction object.
int addTransactionInput(Transaction *self, TransactionInput *input)
Adds a TransactionInput to a Transaction Object.
self The Transaction object. input The TransactionInput object to add to the self Transaction 1 if the transaction input was added successfully and 0 on error.
References FALSE, incrementReferenceCount, TRUE.
int addTransactionOutput(Transaction *self, TransactionOutput *output)
Adds an TransactionOutput to the Transaction.
self The Transaction object. output The TransactionOutput object to add to the self Transaction. 1 if the transaction output was added successfully and 0 on error.
References FALSE, incrementReferenceCount, TRUE.
void calculateTransactionHash(Transaction *self)
References getByteArrayData, getMessage, ByteArray::length, Sha256.
Referenced by getTransactionHash.
uint8_t* getTransactionHash(Transaction *self)
Retrieves or calculates the hash for a transaction. Hashes taken from this function are cached.
self The Transaction object. This should be serialised. The hash for the transaction. This is a 32 byte long, double SHA-256 hash and is a pointer to the hash field in the transaction.
References calculateTransactionHash.
uint32_t calculateTransactionLength(Transaction *self)
Calculates the length of an Transaction; this is needed to serialise the object.
self The Transaction object. The length of the Transaction on success, 0 on failure.
References getSizeOfVarLenInt, TX_INPUT_FIELD_SIZE_EXCLUDING_SCRIPT, TX_LOCKTIME_FIELD_SIZE, TX_OUTPUT_FIELD_SIZE_EXCLUDING_SCRIPT, TX_VERSION_FIELD_SIZE.
Referenced by calculateBlockLength.
int isCoinBase(Transaction *self)
Determines if a transaction is a coinbase transaction or not.
self The Transaction object. 1 if the transaction is a coin-base transaction or 0 if not.
References isNullByteArray.
uint32_t serializeTransaction(Transaction *self)
Serialises a Transaction to byte data.
self The Transaction object. The length read on success, 0 on failure.
References Message::bytes, createVarLenIntFromUInt64, decrementReferenceCount, destroyObject, encodeVarLenInt, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_NULL_BYTES, getByteArraySubsectionReference, getMessage, ByteArray::length, Message::onErrorReceived, serializeTransactionInput, serializeTransactionOutput, VarLenInt::storageSize, writeInt32AsLittleEndianIntoByteArray.
Referenced by dealWithSerializationTran.
uint32_t deserializeTransaction(Transaction *self)
Deserialises a Transaction so that it can be used as an object.
self The Transaction object The length read on success, 0 on failure.
References Message::bytes, createNewTransactionInputFromData, createNewTransactionOutputFromData, decodeVarLenInt, decrementReferenceCount, deserializeTransactionInput, deserializeTransactionOutput, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, ERROR_OUT_OF_MEMORY, getByteArraySubsectionReference, getMessage, ByteArray::length, Message::onErrorReceived, readInt32AsLittleEndianFromByteArray, VarLenInt::storageSize, VarLenInt::value.
Referenced by deserializeWithTransactions.
TransactionHashStatus getTransactionInputHashForVerification(void *vself, ByteArray *prevOutSubScript, uint32_t input, SignatureType signType, uint8_t *hash)
Gets the hash for signing or signature checking for a transaction input. The transaction input needs to contain the outPointerHash, outPointerIndex and sequence. If these are modifed afterwards then the signiture is invalid.
TRANSACTION SIGNING vself The Transaction object. prevOutSubScript The sub script from the output. Must be the correct one or the signiture will be invalid. input The index of the input to sign. signType The type of signature to get the data for. hash The 32 byte data hash for signing or checking signatures. _TX_HASH_OK if the hash has been retreived with no problems. _TX_HASH_BAD is returned if the hash is invalid and _TX_HASH_ERR is returned upon an error.
References copyByteArrayToByteArray, createNewByteArrayOfSize, createVarLenIntFromUInt64, encodeVarLenInt, ERROR_TRANSACTION_FEW_INPUTS, ERROR_TRANSACTION_FEW_OUTPUTS, getByteArray, getByteArrayData, getMessage, getSizeOfVarLenInt, ByteArray::length, Message::onErrorReceived, Sha256, SIGHASH_ANYONECANPAY, SIGHASH_NONE, SIGHASH_SINGLE, VarLenInt::storageSize, TX_HASH_BAD, TX_HASH_FAIL, TX_HASH_GOOD, VarLenInt::value, writeInt32AsLittleEndianIntoByteArray, writeInt64AsLittleEndianIntoByteArray.
Referenced by executeScript.
int takeTransactionInput(Transaction *self, TransactionInput *input)
Adds an TransactionInput to the Transaction without retaining it.
self The Transaction object. input The TransactionInput object. true if the transaction input was taken successfully and false on error.
References FALSE, TRUE.
int takeTransactionOutput(Transaction *self, TransactionOutput *output)
Adds an TransactionInput to the CBTransaction without retaining it.
self The Transaction object. input The TransactionOutput object. true if the transaction output was taken successfully and false on error.
References FALSE, TRUE.