TransactionOutput.c
TransactionOutput* createNewTransactionOutput(uint64_t value, Script *script, void(*onErrorReceived)(Error error, char *,...))
Creates a new TransactionOutput object.
A new TransactionOutput object.
References Object::destroy, destroyTransactionOutput, ERROR_OUT_OF_MEMORY, getObject, initializeTransactionOutput.
TransactionOutput* createNewTransactionOutputFromData(ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new TransactionOutput object from byte data. Should be serialised for object data.
A new TransactionOutput object.
References Object::destroy, destroyTransactionOutput, ERROR_OUT_OF_MEMORY, getObject, initializeTransactionOutputFromData.
Referenced by deserializeTransaction.
int initializeTransactionOutput(TransactionOutput *self, uint64_t value, Script *script, void(*onErrorReceived)(Error error, char *,...))
Initialises a TransactionOutput object.
self The TransactionOutput object to initialise. true on success, false on failure.
References FALSE, getMessage, incrementReferenceCount, initializeMessageFromObject, TRUE.
Referenced by createNewTransactionOutput.
int initializeTransactionOutputFromData(TransactionOutput *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initialises a TransactionOutput object.
self The TransactionOutput object to initialise. true on success, false on failure.
References getMessage, initializeMessageFromByteArrayData, TRUE.
Referenced by createNewTransactionOutputFromData.
TransactionOutput* getTransactionOutput(void *self)
Gets a TransactionOutput from another object. Use this to avoid casts.
self The object to obtain the TransactionOutput from. The TransactionOutput object.
void destroyTransactionOutput(void *txOut)
Frees a TransactionOutput object.
self The TransactionOutput object to free.
References decrementReferenceCount, destroyMessage.
Referenced by createNewTransactionOutput, createNewTransactionOutputFromData.
uint32_t serializeTransactionOutput(TransactionOutput *self)
Serialises a TransactionOutput to byte data.
self The TransactionOutput object The length written on success, 0 on failure.
References Message::bytes, changeByteArrayDataReference, copyByteArrayToByteArray, createVarLenIntFromUInt64, encodeVarLenInt, ERROR_MESSAGE_SERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_BAD_DATA, ERROR_MESSAGE_SERIALISATION_NULL_BYTES, getByteArray, getMessage, ByteArray::length, Message::onErrorReceived, VarLenInt::storageSize, writeInt64AsLittleEndianIntoByteArray.
Referenced by serializeTransaction.
uint32_t deserializeTransactionOutput(TransactionOutput *self)
Deserialises a TransactionOutput so that it can be used as an object.
self The TransactionOutput object The length read on success, 0 on failure.
References Message::bytes, createNewScriptFromReference, decodeVarLenInt, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, getByteFromByteArray, getMessage, ByteArray::length, Message::onErrorReceived, readInt64AsLittleEndianFromByteArray, VarLenInt::storageSize, VarLenInt::value.
Referenced by deserializeTransaction.