TransactionInput.h
TransactionInput* createNewTransactionInput(Script *script, uint32_t sequence, ByteArray *prevOutputHash, uint32_t prevOutputIndex, void(*onErrorReceived)(Error error, char *,...))
Creates a new TransactionInput object with no inputs or outputs.
script Computational Script for confirming transaction authorization sequence Transaction version as defined by the sender. Intended for "replacement" of transactions when information is updated before inclusion into a block. prevOutputHash. The hash of the previous transaction. prevOutputIndex Index of the previous transaction onErrorReceived Error handler new TransactionInput object.
References Object::destroy, destroyTransactionInput, ERROR_OUT_OF_MEMORY, getObject, initializeTransactionInput.
TransactionInput* createNewTransactionInputFromData(ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Creates a new TransactionInput from byteArray.
data. Raw data to create a transactionInput onErrorReceived Error handler new TransactionInput object.
References Object::destroy, destroyTransactionInput, ERROR_OUT_OF_MEMORY, getObject, initializeTransactionInputFromData.
Referenced by deserializeTransaction.
int initializeTransactionInput(TransactionInput *self, Script *script, uint32_t sequence, ByteArray *prevOutHash, uint32_t prevOutIndex, void(*onErrorReceived)(Error error, char *,...))
Initializes a TransactionInput object.
self The TransactionInput object script Computational Script for confirming transaction authorization sequence Transaction version as defined by the sender. Intended for "replacement" of transactions when information is updated before inclusion into a block. prevOutputHash. The hash of the previous transaction. prevOutputIndex Index of the previous transaction onErrorReceived Error handler TRUE on success, FALSE on failure.
References FALSE, getMessage, incrementReferenceCount, initializeMessageFromObject, TRUE.
Referenced by createNewTransactionInput.
int initializeTransactionInputFromData(TransactionInput *self, ByteArray *data, void(*onErrorReceived)(Error error, char *,...))
Initializes a new TransactionInput object from the ByteArray.
self The TransactionInput object to initialize data The byte data. onErrorReceived Error handler true on success, false on failure.
References FALSE, getMessage, initializeMessageFromByteArrayData, TRUE.
Referenced by createNewTransactionInputFromData.
TransactionInput* getTransactionInput(void *self)
brief Gets a TransactionInput from another object. Use this to avoid casts
self The TransactionInput object TransactionInput object
void destroyTransactionInput(void *self)
Frees a TransactionInput object.
self the TransactionInput object void
References decrementReferenceCount, destroyMessage.
Referenced by createNewTransactionInput, createNewTransactionInputFromData.
uint32_t serializeTransactionInput(TransactionInput *self)
Serializes a TransactionInput to byte data.
self the TransactionInput object the length written on success, 0 on failure
References Message::bytes, changeByteArrayDataReference, copyByteArrayToByteArray, createVarLenIntFromUInt64, encodeVarLenInt, ERROR_MESSAGE_SERIALISATION_BAD_BYTES, ERROR_MESSAGE_SERIALISATION_BAD_DATA, ERROR_MESSAGE_SERIALISATION_NULL_BYTES, getByteArray, getMessage, ByteArray::length, Message::onErrorReceived, VarLenInt::storageSize, writeInt32AsLittleEndianIntoByteArray.
Referenced by serializeTransaction.
uint32_t deserializeTransactionInput(TransactionInput *self)
deserializes a TransactionInput so that it can be used as an object
self The TransactionInput object The length read on success, 0 on failure.
References Message::bytes, createNewScriptFromReference, decodeVarLenInt, decrementReferenceCount, ERROR_INIT_FAIL, ERROR_MESSAGE_DESERIALISATION_BAD_BYTES, ERROR_MESSAGE_DESERIALISATION_NULL_BYTES, getByteArraySubsectionReference, getMessage, ByteArray::length, Message::onErrorReceived, readInt32AsLittleEndianFromByteArray, VarLenInt::storageSize, VarLenInt::value.
Referenced by deserializeTransaction.