VersionChecksumBytes.h
VersionChecksumBytes* NewVersionChecksumBytesFromString(ByteArray *string, int cacheString, void(*onErrorReceived)(Error error, char *,...))
Creates a new VersionChecksumBytes object from a base-58 encoded string. The base-58 string will be validated by it's checksum. This returns NULL if the string is invalid. The _ERROR_BASE58_DECODE_CHECK_TOO_SHORT error is given if the decoded data is less than 4 bytes. _ERROR_BASE58_DECODE_CHECK_INVALID is given if the checksum does not match.
string A base-58 encoded String to make a VersionChecksumBytes object with a termination character. cacheString If true, the bitcoin string for this object will be cached in memory. onErrorReceived A Engine for errors. A new VersionChecksumBytes object or NULL on failure.
References Object::destroy, ERROR_OUT_OF_MEMORY, FreeVersionChecksumBytes, getObject, InitVersionChecksumBytesFromString.
VersionChecksumBytes* NewVersionChecksumBytesFromBytes(uint8_t *bytes, uint32_t size, int cacheString, void(*onErrorReceived)(Error error, char *,...))
Creates a new VersionChecksumBytes object from bytes.
bytes The bytes for the VersionChecksumBytes object. size The size of the byte data. cacheString If true, the bitcoin string for this object will be cached in memory. onErrorReceived A Engine for errors. A new VersionChecksumBytes object.
VersionChecksumBytes* GetVersionChecksumBytes(void *self)
Gets a VersionChecksumBytes from another object. Use this to avoid casts.
self The object to obtain the VersionChecksumBytes from. The VersionChecksumBytes object.
Referenced by FreeAddress, InitAddressFromRIPEMD160Hash.
int InitVersionChecksumBytesFromString(VersionChecksumBytes *self, ByteArray *string, int cacheString, void(*onErrorReceived)(Error error, char *,...))
Initialises a VersionChecksumBytes object from a string.
self The VersionChecksumBytes object to initialise. string A String to make a VersionChecksumBytes object with a termination character. cacheString If true, the bitcoin string for this object will be cached in memory. onErrorReceived A Engine for errors. true on success, false on failure.
References BigIntAlloc, BigInt::data, FALSE, getByteArray, incrementReferenceCount, initNewByteArrayFromData, BigInt::length, reverseBytes, TRUE.
Referenced by NewVersionChecksumBytesFromString.
int InitVersionChecksumBytesFromBytes(VersionChecksumBytes *self, uint8_t *bytes, uint32_t size, int cacheString, void(*onErrorReceived)(Error error, char *,...))
Initialises a new VersionChecksumBytes object from bytes.
self The VersionChecksumBytes object to initialise. bytes The bytes for the VersionChecksumBytes object. size The size of the byte data. cacheString If true, the bitcoin string for this object will be cached in memory. onErrorReceived A Engine for errors. true on success, false on failure.
References FALSE, getByteArray, initNewByteArrayFromData, TRUE.
Referenced by InitAddressFromRIPEMD160Hash.
void FreeVersionChecksumBytes(void *self)
Frees a VersionChecksumBytes object.
self The VersionChecksumBytes object to free.
References decrementReferenceCount, destroyByteArray, getByteArray.
Referenced by FreeAddress, NewVersionChecksumBytesFromString.
uint8_t VersionChecksumBytesGetVersion(VersionChecksumBytes *self)
Gets the version for a VersionChecksumBytes object.
self The VersionChecksumBytes object. The version code. The Macros _PRODUCTION_NETWORK and _TEST_NETWORK should correspond to this.
References getByteArray, getByteFromByteArray.
ByteArray* VersionChecksumBytesGetString(VersionChecksumBytes *self)
Gets the string representation for a VersionChecksumBytes object as a base-58 encoded String.
self The VersionChecksumBytes object. The object represented as a base-58 encoded String. Do not modify this. Copy if modification is required.